#include <wchar.h>
#include "tests/strings/cxxwrapper.h"
//===----------------------------------------------------------------------===//
//
//                     The LLVM Compiler Infrastructure
//
// This file is dual licensed under the MIT and the University of Illinois Open
// Source Licenses. See LICENSE.TXT for details.
//
//===----------------------------------------------------------------------===//

// <string>

// int compare(size_type pos, size_type n1, const charT *s, size_type n2) const;

#include <string>
#include <stdexcept>
#include <cassert>

#include "tests/support/min_allocator.h"

int sign(int x)
{
    if (x == 0)
        return 0;
    if (x < 0)
        return -1;
    return 1;
}

template <class S>
void
test(const S& s, typename S::size_type pos, typename S::size_type n1,
     const typename S::value_type* str, typename S::size_type n2, int x)
{
    try
    {
        assert(sign(s.compare(pos, n1, str, n2)) == sign(x));
        assert(pos <= s.size());
    }
    catch (std::out_of_range&)
    {
        assert(pos > s.size());
    }
}

template <class S>
void test0()
{
    test(S(L""), 0, 0, L"", 0, 0);
    test(S(L""), 0, 0, L"abcde", 0, 0);
    test(S(L""), 0, 0, L"abcde", 1, -1);
    test(S(L""), 0, 0, L"abcde", 2, -2);
    test(S(L""), 0, 0, L"abcde", 4, -4);
    test(S(L""), 0, 0, L"abcde", 5, -5);
    test(S(L""), 0, 0, L"abcdefghij", 0, 0);
    test(S(L""), 0, 0, L"abcdefghij", 1, -1);
    test(S(L""), 0, 0, L"abcdefghij", 5, -5);
    test(S(L""), 0, 0, L"abcdefghij", 9, -9);
    test(S(L""), 0, 0, L"abcdefghij", 10, -10);
    test(S(L""), 0, 0, L"abcdefghijklmnopqrst", 0, 0);
    test(S(L""), 0, 0, L"abcdefghijklmnopqrst", 1, -1);
    test(S(L""), 0, 0, L"abcdefghijklmnopqrst", 10, -10);
    test(S(L""), 0, 0, L"abcdefghijklmnopqrst", 19, -19);
    test(S(L""), 0, 0, L"abcdefghijklmnopqrst", 20, -20);
    test(S(L""), 0, 1, L"", 0, 0);
    test(S(L""), 0, 1, L"abcde", 0, 0);
    test(S(L""), 0, 1, L"abcde", 1, -1);
    test(S(L""), 0, 1, L"abcde", 2, -2);
    test(S(L""), 0, 1, L"abcde", 4, -4);
    test(S(L""), 0, 1, L"abcde", 5, -5);
    test(S(L""), 0, 1, L"abcdefghij", 0, 0);
    test(S(L""), 0, 1, L"abcdefghij", 1, -1);
    test(S(L""), 0, 1, L"abcdefghij", 5, -5);
    test(S(L""), 0, 1, L"abcdefghij", 9, -9);
    test(S(L""), 0, 1, L"abcdefghij", 10, -10);
    test(S(L""), 0, 1, L"abcdefghijklmnopqrst", 0, 0);
    test(S(L""), 0, 1, L"abcdefghijklmnopqrst", 1, -1);
    test(S(L""), 0, 1, L"abcdefghijklmnopqrst", 10, -10);
    test(S(L""), 0, 1, L"abcdefghijklmnopqrst", 19, -19);
    test(S(L""), 0, 1, L"abcdefghijklmnopqrst", 20, -20);
    test(S(L""), 1, 0, L"", 0, 0);
    test(S(L""), 1, 0, L"abcde", 0, 0);
    test(S(L""), 1, 0, L"abcde", 1, 0);
    test(S(L""), 1, 0, L"abcde", 2, 0);
    test(S(L""), 1, 0, L"abcde", 4, 0);
    test(S(L""), 1, 0, L"abcde", 5, 0);
    test(S(L""), 1, 0, L"abcdefghij", 0, 0);
    test(S(L""), 1, 0, L"abcdefghij", 1, 0);
    test(S(L""), 1, 0, L"abcdefghij", 5, 0);
    test(S(L""), 1, 0, L"abcdefghij", 9, 0);
    test(S(L""), 1, 0, L"abcdefghij", 10, 0);
    test(S(L""), 1, 0, L"abcdefghijklmnopqrst", 0, 0);
    test(S(L""), 1, 0, L"abcdefghijklmnopqrst", 1, 0);
    test(S(L""), 1, 0, L"abcdefghijklmnopqrst", 10, 0);
    test(S(L""), 1, 0, L"abcdefghijklmnopqrst", 19, 0);
    test(S(L""), 1, 0, L"abcdefghijklmnopqrst", 20, 0);
    test(S(L"abcde"), 0, 0, L"", 0, 0);
    test(S(L"abcde"), 0, 0, L"abcde", 0, 0);
    test(S(L"abcde"), 0, 0, L"abcde", 1, -1);
    test(S(L"abcde"), 0, 0, L"abcde", 2, -2);
    test(S(L"abcde"), 0, 0, L"abcde", 4, -4);
    test(S(L"abcde"), 0, 0, L"abcde", 5, -5);
    test(S(L"abcde"), 0, 0, L"abcdefghij", 0, 0);
    test(S(L"abcde"), 0, 0, L"abcdefghij", 1, -1);
    test(S(L"abcde"), 0, 0, L"abcdefghij", 5, -5);
    test(S(L"abcde"), 0, 0, L"abcdefghij", 9, -9);
    test(S(L"abcde"), 0, 0, L"abcdefghij", 10, -10);
    test(S(L"abcde"), 0, 0, L"abcdefghijklmnopqrst", 0, 0);
    test(S(L"abcde"), 0, 0, L"abcdefghijklmnopqrst", 1, -1);
    test(S(L"abcde"), 0, 0, L"abcdefghijklmnopqrst", 10, -10);
    test(S(L"abcde"), 0, 0, L"abcdefghijklmnopqrst", 19, -19);
    test(S(L"abcde"), 0, 0, L"abcdefghijklmnopqrst", 20, -20);
    test(S(L"abcde"), 0, 1, L"", 0, 1);
    test(S(L"abcde"), 0, 1, L"abcde", 0, 1);
    test(S(L"abcde"), 0, 1, L"abcde", 1, 0);
    test(S(L"abcde"), 0, 1, L"abcde", 2, -1);
    test(S(L"abcde"), 0, 1, L"abcde", 4, -3);
    test(S(L"abcde"), 0, 1, L"abcde", 5, -4);
    test(S(L"abcde"), 0, 1, L"abcdefghij", 0, 1);
    test(S(L"abcde"), 0, 1, L"abcdefghij", 1, 0);
    test(S(L"abcde"), 0, 1, L"abcdefghij", 5, -4);
    test(S(L"abcde"), 0, 1, L"abcdefghij", 9, -8);
    test(S(L"abcde"), 0, 1, L"abcdefghij", 10, -9);
    test(S(L"abcde"), 0, 1, L"abcdefghijklmnopqrst", 0, 1);
    test(S(L"abcde"), 0, 1, L"abcdefghijklmnopqrst", 1, 0);
    test(S(L"abcde"), 0, 1, L"abcdefghijklmnopqrst", 10, -9);
    test(S(L"abcde"), 0, 1, L"abcdefghijklmnopqrst", 19, -18);
    test(S(L"abcde"), 0, 1, L"abcdefghijklmnopqrst", 20, -19);
    test(S(L"abcde"), 0, 2, L"", 0, 2);
    test(S(L"abcde"), 0, 2, L"abcde", 0, 2);
    test(S(L"abcde"), 0, 2, L"abcde", 1, 1);
    test(S(L"abcde"), 0, 2, L"abcde", 2, 0);
    test(S(L"abcde"), 0, 2, L"abcde", 4, -2);
    test(S(L"abcde"), 0, 2, L"abcde", 5, -3);
    test(S(L"abcde"), 0, 2, L"abcdefghij", 0, 2);
    test(S(L"abcde"), 0, 2, L"abcdefghij", 1, 1);
    test(S(L"abcde"), 0, 2, L"abcdefghij", 5, -3);
    test(S(L"abcde"), 0, 2, L"abcdefghij", 9, -7);
    test(S(L"abcde"), 0, 2, L"abcdefghij", 10, -8);
    test(S(L"abcde"), 0, 2, L"abcdefghijklmnopqrst", 0, 2);
    test(S(L"abcde"), 0, 2, L"abcdefghijklmnopqrst", 1, 1);
    test(S(L"abcde"), 0, 2, L"abcdefghijklmnopqrst", 10, -8);
    test(S(L"abcde"), 0, 2, L"abcdefghijklmnopqrst", 19, -17);
    test(S(L"abcde"), 0, 2, L"abcdefghijklmnopqrst", 20, -18);
    test(S(L"abcde"), 0, 4, L"", 0, 4);
    test(S(L"abcde"), 0, 4, L"abcde", 0, 4);
    test(S(L"abcde"), 0, 4, L"abcde", 1, 3);
    test(S(L"abcde"), 0, 4, L"abcde", 2, 2);
}

template <class S>
void test1()
{
    test(S(L"abcde"), 0, 4, L"abcde", 4, 0);
    test(S(L"abcde"), 0, 4, L"abcde", 5, -1);
    test(S(L"abcde"), 0, 4, L"abcdefghij", 0, 4);
    test(S(L"abcde"), 0, 4, L"abcdefghij", 1, 3);
    test(S(L"abcde"), 0, 4, L"abcdefghij", 5, -1);
    test(S(L"abcde"), 0, 4, L"abcdefghij", 9, -5);
    test(S(L"abcde"), 0, 4, L"abcdefghij", 10, -6);
    test(S(L"abcde"), 0, 4, L"abcdefghijklmnopqrst", 0, 4);
    test(S(L"abcde"), 0, 4, L"abcdefghijklmnopqrst", 1, 3);
    test(S(L"abcde"), 0, 4, L"abcdefghijklmnopqrst", 10, -6);
    test(S(L"abcde"), 0, 4, L"abcdefghijklmnopqrst", 19, -15);
    test(S(L"abcde"), 0, 4, L"abcdefghijklmnopqrst", 20, -16);
    test(S(L"abcde"), 0, 5, L"", 0, 5);
    test(S(L"abcde"), 0, 5, L"abcde", 0, 5);
    test(S(L"abcde"), 0, 5, L"abcde", 1, 4);
    test(S(L"abcde"), 0, 5, L"abcde", 2, 3);
    test(S(L"abcde"), 0, 5, L"abcde", 4, 1);
    test(S(L"abcde"), 0, 5, L"abcde", 5, 0);
    test(S(L"abcde"), 0, 5, L"abcdefghij", 0, 5);
    test(S(L"abcde"), 0, 5, L"abcdefghij", 1, 4);
    test(S(L"abcde"), 0, 5, L"abcdefghij", 5, 0);
    test(S(L"abcde"), 0, 5, L"abcdefghij", 9, -4);
    test(S(L"abcde"), 0, 5, L"abcdefghij", 10, -5);
    test(S(L"abcde"), 0, 5, L"abcdefghijklmnopqrst", 0, 5);
    test(S(L"abcde"), 0, 5, L"abcdefghijklmnopqrst", 1, 4);
    test(S(L"abcde"), 0, 5, L"abcdefghijklmnopqrst", 10, -5);
    test(S(L"abcde"), 0, 5, L"abcdefghijklmnopqrst", 19, -14);
    test(S(L"abcde"), 0, 5, L"abcdefghijklmnopqrst", 20, -15);
    test(S(L"abcde"), 0, 6, L"", 0, 5);
    test(S(L"abcde"), 0, 6, L"abcde", 0, 5);
    test(S(L"abcde"), 0, 6, L"abcde", 1, 4);
    test(S(L"abcde"), 0, 6, L"abcde", 2, 3);
    test(S(L"abcde"), 0, 6, L"abcde", 4, 1);
    test(S(L"abcde"), 0, 6, L"abcde", 5, 0);
    test(S(L"abcde"), 0, 6, L"abcdefghij", 0, 5);
    test(S(L"abcde"), 0, 6, L"abcdefghij", 1, 4);
    test(S(L"abcde"), 0, 6, L"abcdefghij", 5, 0);
    test(S(L"abcde"), 0, 6, L"abcdefghij", 9, -4);
    test(S(L"abcde"), 0, 6, L"abcdefghij", 10, -5);
    test(S(L"abcde"), 0, 6, L"abcdefghijklmnopqrst", 0, 5);
    test(S(L"abcde"), 0, 6, L"abcdefghijklmnopqrst", 1, 4);
    test(S(L"abcde"), 0, 6, L"abcdefghijklmnopqrst", 10, -5);
    test(S(L"abcde"), 0, 6, L"abcdefghijklmnopqrst", 19, -14);
    test(S(L"abcde"), 0, 6, L"abcdefghijklmnopqrst", 20, -15);
    test(S(L"abcde"), 1, 0, L"", 0, 0);
    test(S(L"abcde"), 1, 0, L"abcde", 0, 0);
    test(S(L"abcde"), 1, 0, L"abcde", 1, -1);
    test(S(L"abcde"), 1, 0, L"abcde", 2, -2);
    test(S(L"abcde"), 1, 0, L"abcde", 4, -4);
    test(S(L"abcde"), 1, 0, L"abcde", 5, -5);
    test(S(L"abcde"), 1, 0, L"abcdefghij", 0, 0);
    test(S(L"abcde"), 1, 0, L"abcdefghij", 1, -1);
    test(S(L"abcde"), 1, 0, L"abcdefghij", 5, -5);
    test(S(L"abcde"), 1, 0, L"abcdefghij", 9, -9);
    test(S(L"abcde"), 1, 0, L"abcdefghij", 10, -10);
    test(S(L"abcde"), 1, 0, L"abcdefghijklmnopqrst", 0, 0);
    test(S(L"abcde"), 1, 0, L"abcdefghijklmnopqrst", 1, -1);
    test(S(L"abcde"), 1, 0, L"abcdefghijklmnopqrst", 10, -10);
    test(S(L"abcde"), 1, 0, L"abcdefghijklmnopqrst", 19, -19);
    test(S(L"abcde"), 1, 0, L"abcdefghijklmnopqrst", 20, -20);
    test(S(L"abcde"), 1, 1, L"", 0, 1);
    test(S(L"abcde"), 1, 1, L"abcde", 0, 1);
    test(S(L"abcde"), 1, 1, L"abcde", 1, 1);
    test(S(L"abcde"), 1, 1, L"abcde", 2, 1);
    test(S(L"abcde"), 1, 1, L"abcde", 4, 1);
    test(S(L"abcde"), 1, 1, L"abcde", 5, 1);
    test(S(L"abcde"), 1, 1, L"abcdefghij", 0, 1);
    test(S(L"abcde"), 1, 1, L"abcdefghij", 1, 1);
    test(S(L"abcde"), 1, 1, L"abcdefghij", 5, 1);
    test(S(L"abcde"), 1, 1, L"abcdefghij", 9, 1);
    test(S(L"abcde"), 1, 1, L"abcdefghij", 10, 1);
    test(S(L"abcde"), 1, 1, L"abcdefghijklmnopqrst", 0, 1);
    test(S(L"abcde"), 1, 1, L"abcdefghijklmnopqrst", 1, 1);
    test(S(L"abcde"), 1, 1, L"abcdefghijklmnopqrst", 10, 1);
    test(S(L"abcde"), 1, 1, L"abcdefghijklmnopqrst", 19, 1);
    test(S(L"abcde"), 1, 1, L"abcdefghijklmnopqrst", 20, 1);
    test(S(L"abcde"), 1, 2, L"", 0, 2);
    test(S(L"abcde"), 1, 2, L"abcde", 0, 2);
    test(S(L"abcde"), 1, 2, L"abcde", 1, 1);
    test(S(L"abcde"), 1, 2, L"abcde", 2, 1);
    test(S(L"abcde"), 1, 2, L"abcde", 4, 1);
    test(S(L"abcde"), 1, 2, L"abcde", 5, 1);
    test(S(L"abcde"), 1, 2, L"abcdefghij", 0, 2);
    test(S(L"abcde"), 1, 2, L"abcdefghij", 1, 1);
    test(S(L"abcde"), 1, 2, L"abcdefghij", 5, 1);
    test(S(L"abcde"), 1, 2, L"abcdefghij", 9, 1);
    test(S(L"abcde"), 1, 2, L"abcdefghij", 10, 1);
    test(S(L"abcde"), 1, 2, L"abcdefghijklmnopqrst", 0, 2);
    test(S(L"abcde"), 1, 2, L"abcdefghijklmnopqrst", 1, 1);
    test(S(L"abcde"), 1, 2, L"abcdefghijklmnopqrst", 10, 1);
    test(S(L"abcde"), 1, 2, L"abcdefghijklmnopqrst", 19, 1);
    test(S(L"abcde"), 1, 2, L"abcdefghijklmnopqrst", 20, 1);
    test(S(L"abcde"), 1, 3, L"", 0, 3);
    test(S(L"abcde"), 1, 3, L"abcde", 0, 3);
    test(S(L"abcde"), 1, 3, L"abcde", 1, 1);
    test(S(L"abcde"), 1, 3, L"abcde", 2, 1);
    test(S(L"abcde"), 1, 3, L"abcde", 4, 1);
    test(S(L"abcde"), 1, 3, L"abcde", 5, 1);
    test(S(L"abcde"), 1, 3, L"abcdefghij", 0, 3);
    test(S(L"abcde"), 1, 3, L"abcdefghij", 1, 1);
}

template <class S>
void test2()
{
    test(S(L"abcde"), 1, 3, L"abcdefghij", 5, 1);
    test(S(L"abcde"), 1, 3, L"abcdefghij", 9, 1);
    test(S(L"abcde"), 1, 3, L"abcdefghij", 10, 1);
    test(S(L"abcde"), 1, 3, L"abcdefghijklmnopqrst", 0, 3);
    test(S(L"abcde"), 1, 3, L"abcdefghijklmnopqrst", 1, 1);
    test(S(L"abcde"), 1, 3, L"abcdefghijklmnopqrst", 10, 1);
    test(S(L"abcde"), 1, 3, L"abcdefghijklmnopqrst", 19, 1);
    test(S(L"abcde"), 1, 3, L"abcdefghijklmnopqrst", 20, 1);
    test(S(L"abcde"), 1, 4, L"", 0, 4);
    test(S(L"abcde"), 1, 4, L"abcde", 0, 4);
    test(S(L"abcde"), 1, 4, L"abcde", 1, 1);
    test(S(L"abcde"), 1, 4, L"abcde", 2, 1);
    test(S(L"abcde"), 1, 4, L"abcde", 4, 1);
    test(S(L"abcde"), 1, 4, L"abcde", 5, 1);
    test(S(L"abcde"), 1, 4, L"abcdefghij", 0, 4);
    test(S(L"abcde"), 1, 4, L"abcdefghij", 1, 1);
    test(S(L"abcde"), 1, 4, L"abcdefghij", 5, 1);
    test(S(L"abcde"), 1, 4, L"abcdefghij", 9, 1);
    test(S(L"abcde"), 1, 4, L"abcdefghij", 10, 1);
    test(S(L"abcde"), 1, 4, L"abcdefghijklmnopqrst", 0, 4);
    test(S(L"abcde"), 1, 4, L"abcdefghijklmnopqrst", 1, 1);
    test(S(L"abcde"), 1, 4, L"abcdefghijklmnopqrst", 10, 1);
    test(S(L"abcde"), 1, 4, L"abcdefghijklmnopqrst", 19, 1);
    test(S(L"abcde"), 1, 4, L"abcdefghijklmnopqrst", 20, 1);
    test(S(L"abcde"), 1, 5, L"", 0, 4);
    test(S(L"abcde"), 1, 5, L"abcde", 0, 4);
    test(S(L"abcde"), 1, 5, L"abcde", 1, 1);
    test(S(L"abcde"), 1, 5, L"abcde", 2, 1);
    test(S(L"abcde"), 1, 5, L"abcde", 4, 1);
    test(S(L"abcde"), 1, 5, L"abcde", 5, 1);
    test(S(L"abcde"), 1, 5, L"abcdefghij", 0, 4);
    test(S(L"abcde"), 1, 5, L"abcdefghij", 1, 1);
    test(S(L"abcde"), 1, 5, L"abcdefghij", 5, 1);
    test(S(L"abcde"), 1, 5, L"abcdefghij", 9, 1);
    test(S(L"abcde"), 1, 5, L"abcdefghij", 10, 1);
    test(S(L"abcde"), 1, 5, L"abcdefghijklmnopqrst", 0, 4);
    test(S(L"abcde"), 1, 5, L"abcdefghijklmnopqrst", 1, 1);
    test(S(L"abcde"), 1, 5, L"abcdefghijklmnopqrst", 10, 1);
    test(S(L"abcde"), 1, 5, L"abcdefghijklmnopqrst", 19, 1);
    test(S(L"abcde"), 1, 5, L"abcdefghijklmnopqrst", 20, 1);
    test(S(L"abcde"), 2, 0, L"", 0, 0);
    test(S(L"abcde"), 2, 0, L"abcde", 0, 0);
    test(S(L"abcde"), 2, 0, L"abcde", 1, -1);
    test(S(L"abcde"), 2, 0, L"abcde", 2, -2);
    test(S(L"abcde"), 2, 0, L"abcde", 4, -4);
    test(S(L"abcde"), 2, 0, L"abcde", 5, -5);
    test(S(L"abcde"), 2, 0, L"abcdefghij", 0, 0);
    test(S(L"abcde"), 2, 0, L"abcdefghij", 1, -1);
    test(S(L"abcde"), 2, 0, L"abcdefghij", 5, -5);
    test(S(L"abcde"), 2, 0, L"abcdefghij", 9, -9);
    test(S(L"abcde"), 2, 0, L"abcdefghij", 10, -10);
    test(S(L"abcde"), 2, 0, L"abcdefghijklmnopqrst", 0, 0);
    test(S(L"abcde"), 2, 0, L"abcdefghijklmnopqrst", 1, -1);
    test(S(L"abcde"), 2, 0, L"abcdefghijklmnopqrst", 10, -10);
    test(S(L"abcde"), 2, 0, L"abcdefghijklmnopqrst", 19, -19);
    test(S(L"abcde"), 2, 0, L"abcdefghijklmnopqrst", 20, -20);
    test(S(L"abcde"), 2, 1, L"", 0, 1);
    test(S(L"abcde"), 2, 1, L"abcde", 0, 1);
    test(S(L"abcde"), 2, 1, L"abcde", 1, 2);
    test(S(L"abcde"), 2, 1, L"abcde", 2, 2);
    test(S(L"abcde"), 2, 1, L"abcde", 4, 2);
    test(S(L"abcde"), 2, 1, L"abcde", 5, 2);
    test(S(L"abcde"), 2, 1, L"abcdefghij", 0, 1);
    test(S(L"abcde"), 2, 1, L"abcdefghij", 1, 2);
    test(S(L"abcde"), 2, 1, L"abcdefghij", 5, 2);
    test(S(L"abcde"), 2, 1, L"abcdefghij", 9, 2);
    test(S(L"abcde"), 2, 1, L"abcdefghij", 10, 2);
    test(S(L"abcde"), 2, 1, L"abcdefghijklmnopqrst", 0, 1);
    test(S(L"abcde"), 2, 1, L"abcdefghijklmnopqrst", 1, 2);
    test(S(L"abcde"), 2, 1, L"abcdefghijklmnopqrst", 10, 2);
    test(S(L"abcde"), 2, 1, L"abcdefghijklmnopqrst", 19, 2);
    test(S(L"abcde"), 2, 1, L"abcdefghijklmnopqrst", 20, 2);
    test(S(L"abcde"), 2, 2, L"", 0, 2);
    test(S(L"abcde"), 2, 2, L"abcde", 0, 2);
    test(S(L"abcde"), 2, 2, L"abcde", 1, 2);
    test(S(L"abcde"), 2, 2, L"abcde", 2, 2);
    test(S(L"abcde"), 2, 2, L"abcde", 4, 2);
    test(S(L"abcde"), 2, 2, L"abcde", 5, 2);
    test(S(L"abcde"), 2, 2, L"abcdefghij", 0, 2);
    test(S(L"abcde"), 2, 2, L"abcdefghij", 1, 2);
    test(S(L"abcde"), 2, 2, L"abcdefghij", 5, 2);
    test(S(L"abcde"), 2, 2, L"abcdefghij", 9, 2);
    test(S(L"abcde"), 2, 2, L"abcdefghij", 10, 2);
    test(S(L"abcde"), 2, 2, L"abcdefghijklmnopqrst", 0, 2);
    test(S(L"abcde"), 2, 2, L"abcdefghijklmnopqrst", 1, 2);
    test(S(L"abcde"), 2, 2, L"abcdefghijklmnopqrst", 10, 2);
    test(S(L"abcde"), 2, 2, L"abcdefghijklmnopqrst", 19, 2);
    test(S(L"abcde"), 2, 2, L"abcdefghijklmnopqrst", 20, 2);
    test(S(L"abcde"), 2, 3, L"", 0, 3);
    test(S(L"abcde"), 2, 3, L"abcde", 0, 3);
    test(S(L"abcde"), 2, 3, L"abcde", 1, 2);
    test(S(L"abcde"), 2, 3, L"abcde", 2, 2);
    test(S(L"abcde"), 2, 3, L"abcde", 4, 2);
    test(S(L"abcde"), 2, 3, L"abcde", 5, 2);
    test(S(L"abcde"), 2, 3, L"abcdefghij", 0, 3);
    test(S(L"abcde"), 2, 3, L"abcdefghij", 1, 2);
    test(S(L"abcde"), 2, 3, L"abcdefghij", 5, 2);
    test(S(L"abcde"), 2, 3, L"abcdefghij", 9, 2);
    test(S(L"abcde"), 2, 3, L"abcdefghij", 10, 2);
    test(S(L"abcde"), 2, 3, L"abcdefghijklmnopqrst", 0, 3);
}

template <class S>
void test3()
{
    test(S(L"abcde"), 2, 3, L"abcdefghijklmnopqrst", 1, 2);
    test(S(L"abcde"), 2, 3, L"abcdefghijklmnopqrst", 10, 2);
    test(S(L"abcde"), 2, 3, L"abcdefghijklmnopqrst", 19, 2);
    test(S(L"abcde"), 2, 3, L"abcdefghijklmnopqrst", 20, 2);
    test(S(L"abcde"), 2, 4, L"", 0, 3);
    test(S(L"abcde"), 2, 4, L"abcde", 0, 3);
    test(S(L"abcde"), 2, 4, L"abcde", 1, 2);
    test(S(L"abcde"), 2, 4, L"abcde", 2, 2);
    test(S(L"abcde"), 2, 4, L"abcde", 4, 2);
    test(S(L"abcde"), 2, 4, L"abcde", 5, 2);
    test(S(L"abcde"), 2, 4, L"abcdefghij", 0, 3);
    test(S(L"abcde"), 2, 4, L"abcdefghij", 1, 2);
    test(S(L"abcde"), 2, 4, L"abcdefghij", 5, 2);
    test(S(L"abcde"), 2, 4, L"abcdefghij", 9, 2);
    test(S(L"abcde"), 2, 4, L"abcdefghij", 10, 2);
    test(S(L"abcde"), 2, 4, L"abcdefghijklmnopqrst", 0, 3);
    test(S(L"abcde"), 2, 4, L"abcdefghijklmnopqrst", 1, 2);
    test(S(L"abcde"), 2, 4, L"abcdefghijklmnopqrst", 10, 2);
    test(S(L"abcde"), 2, 4, L"abcdefghijklmnopqrst", 19, 2);
    test(S(L"abcde"), 2, 4, L"abcdefghijklmnopqrst", 20, 2);
    test(S(L"abcde"), 4, 0, L"", 0, 0);
    test(S(L"abcde"), 4, 0, L"abcde", 0, 0);
    test(S(L"abcde"), 4, 0, L"abcde", 1, -1);
    test(S(L"abcde"), 4, 0, L"abcde", 2, -2);
    test(S(L"abcde"), 4, 0, L"abcde", 4, -4);
    test(S(L"abcde"), 4, 0, L"abcde", 5, -5);
    test(S(L"abcde"), 4, 0, L"abcdefghij", 0, 0);
    test(S(L"abcde"), 4, 0, L"abcdefghij", 1, -1);
    test(S(L"abcde"), 4, 0, L"abcdefghij", 5, -5);
    test(S(L"abcde"), 4, 0, L"abcdefghij", 9, -9);
    test(S(L"abcde"), 4, 0, L"abcdefghij", 10, -10);
    test(S(L"abcde"), 4, 0, L"abcdefghijklmnopqrst", 0, 0);
    test(S(L"abcde"), 4, 0, L"abcdefghijklmnopqrst", 1, -1);
    test(S(L"abcde"), 4, 0, L"abcdefghijklmnopqrst", 10, -10);
    test(S(L"abcde"), 4, 0, L"abcdefghijklmnopqrst", 19, -19);
    test(S(L"abcde"), 4, 0, L"abcdefghijklmnopqrst", 20, -20);
    test(S(L"abcde"), 4, 1, L"", 0, 1);
    test(S(L"abcde"), 4, 1, L"abcde", 0, 1);
    test(S(L"abcde"), 4, 1, L"abcde", 1, 4);
    test(S(L"abcde"), 4, 1, L"abcde", 2, 4);
    test(S(L"abcde"), 4, 1, L"abcde", 4, 4);
    test(S(L"abcde"), 4, 1, L"abcde", 5, 4);
    test(S(L"abcde"), 4, 1, L"abcdefghij", 0, 1);
    test(S(L"abcde"), 4, 1, L"abcdefghij", 1, 4);
    test(S(L"abcde"), 4, 1, L"abcdefghij", 5, 4);
    test(S(L"abcde"), 4, 1, L"abcdefghij", 9, 4);
    test(S(L"abcde"), 4, 1, L"abcdefghij", 10, 4);
    test(S(L"abcde"), 4, 1, L"abcdefghijklmnopqrst", 0, 1);
    test(S(L"abcde"), 4, 1, L"abcdefghijklmnopqrst", 1, 4);
    test(S(L"abcde"), 4, 1, L"abcdefghijklmnopqrst", 10, 4);
    test(S(L"abcde"), 4, 1, L"abcdefghijklmnopqrst", 19, 4);
    test(S(L"abcde"), 4, 1, L"abcdefghijklmnopqrst", 20, 4);
    test(S(L"abcde"), 4, 2, L"", 0, 1);
    test(S(L"abcde"), 4, 2, L"abcde", 0, 1);
    test(S(L"abcde"), 4, 2, L"abcde", 1, 4);
    test(S(L"abcde"), 4, 2, L"abcde", 2, 4);
    test(S(L"abcde"), 4, 2, L"abcde", 4, 4);
    test(S(L"abcde"), 4, 2, L"abcde", 5, 4);
    test(S(L"abcde"), 4, 2, L"abcdefghij", 0, 1);
    test(S(L"abcde"), 4, 2, L"abcdefghij", 1, 4);
    test(S(L"abcde"), 4, 2, L"abcdefghij", 5, 4);
    test(S(L"abcde"), 4, 2, L"abcdefghij", 9, 4);
    test(S(L"abcde"), 4, 2, L"abcdefghij", 10, 4);
    test(S(L"abcde"), 4, 2, L"abcdefghijklmnopqrst", 0, 1);
    test(S(L"abcde"), 4, 2, L"abcdefghijklmnopqrst", 1, 4);
    test(S(L"abcde"), 4, 2, L"abcdefghijklmnopqrst", 10, 4);
    test(S(L"abcde"), 4, 2, L"abcdefghijklmnopqrst", 19, 4);
    test(S(L"abcde"), 4, 2, L"abcdefghijklmnopqrst", 20, 4);
    test(S(L"abcde"), 5, 0, L"", 0, 0);
    test(S(L"abcde"), 5, 0, L"abcde", 0, 0);
    test(S(L"abcde"), 5, 0, L"abcde", 1, -1);
    test(S(L"abcde"), 5, 0, L"abcde", 2, -2);
    test(S(L"abcde"), 5, 0, L"abcde", 4, -4);
    test(S(L"abcde"), 5, 0, L"abcde", 5, -5);
    test(S(L"abcde"), 5, 0, L"abcdefghij", 0, 0);
    test(S(L"abcde"), 5, 0, L"abcdefghij", 1, -1);
    test(S(L"abcde"), 5, 0, L"abcdefghij", 5, -5);
    test(S(L"abcde"), 5, 0, L"abcdefghij", 9, -9);
    test(S(L"abcde"), 5, 0, L"abcdefghij", 10, -10);
    test(S(L"abcde"), 5, 0, L"abcdefghijklmnopqrst", 0, 0);
    test(S(L"abcde"), 5, 0, L"abcdefghijklmnopqrst", 1, -1);
    test(S(L"abcde"), 5, 0, L"abcdefghijklmnopqrst", 10, -10);
    test(S(L"abcde"), 5, 0, L"abcdefghijklmnopqrst", 19, -19);
    test(S(L"abcde"), 5, 0, L"abcdefghijklmnopqrst", 20, -20);
    test(S(L"abcde"), 5, 1, L"", 0, 0);
    test(S(L"abcde"), 5, 1, L"abcde", 0, 0);
    test(S(L"abcde"), 5, 1, L"abcde", 1, -1);
    test(S(L"abcde"), 5, 1, L"abcde", 2, -2);
    test(S(L"abcde"), 5, 1, L"abcde", 4, -4);
    test(S(L"abcde"), 5, 1, L"abcde", 5, -5);
    test(S(L"abcde"), 5, 1, L"abcdefghij", 0, 0);
    test(S(L"abcde"), 5, 1, L"abcdefghij", 1, -1);
    test(S(L"abcde"), 5, 1, L"abcdefghij", 5, -5);
    test(S(L"abcde"), 5, 1, L"abcdefghij", 9, -9);
    test(S(L"abcde"), 5, 1, L"abcdefghij", 10, -10);
    test(S(L"abcde"), 5, 1, L"abcdefghijklmnopqrst", 0, 0);
    test(S(L"abcde"), 5, 1, L"abcdefghijklmnopqrst", 1, -1);
    test(S(L"abcde"), 5, 1, L"abcdefghijklmnopqrst", 10, -10);
    test(S(L"abcde"), 5, 1, L"abcdefghijklmnopqrst", 19, -19);
    test(S(L"abcde"), 5, 1, L"abcdefghijklmnopqrst", 20, -20);
}

template <class S>
void test4()
{
    test(S(L"abcde"), 6, 0, L"", 0, 0);
    test(S(L"abcde"), 6, 0, L"abcde", 0, 0);
    test(S(L"abcde"), 6, 0, L"abcde", 1, 0);
    test(S(L"abcde"), 6, 0, L"abcde", 2, 0);
    test(S(L"abcde"), 6, 0, L"abcde", 4, 0);
    test(S(L"abcde"), 6, 0, L"abcde", 5, 0);
    test(S(L"abcde"), 6, 0, L"abcdefghij", 0, 0);
    test(S(L"abcde"), 6, 0, L"abcdefghij", 1, 0);
    test(S(L"abcde"), 6, 0, L"abcdefghij", 5, 0);
    test(S(L"abcde"), 6, 0, L"abcdefghij", 9, 0);
    test(S(L"abcde"), 6, 0, L"abcdefghij", 10, 0);
    test(S(L"abcde"), 6, 0, L"abcdefghijklmnopqrst", 0, 0);
    test(S(L"abcde"), 6, 0, L"abcdefghijklmnopqrst", 1, 0);
    test(S(L"abcde"), 6, 0, L"abcdefghijklmnopqrst", 10, 0);
    test(S(L"abcde"), 6, 0, L"abcdefghijklmnopqrst", 19, 0);
    test(S(L"abcde"), 6, 0, L"abcdefghijklmnopqrst", 20, 0);
    test(S(L"abcdefghij"), 0, 0, L"", 0, 0);
    test(S(L"abcdefghij"), 0, 0, L"abcde", 0, 0);
    test(S(L"abcdefghij"), 0, 0, L"abcde", 1, -1);
    test(S(L"abcdefghij"), 0, 0, L"abcde", 2, -2);
    test(S(L"abcdefghij"), 0, 0, L"abcde", 4, -4);
    test(S(L"abcdefghij"), 0, 0, L"abcde", 5, -5);
    test(S(L"abcdefghij"), 0, 0, L"abcdefghij", 0, 0);
    test(S(L"abcdefghij"), 0, 0, L"abcdefghij", 1, -1);
    test(S(L"abcdefghij"), 0, 0, L"abcdefghij", 5, -5);
    test(S(L"abcdefghij"), 0, 0, L"abcdefghij", 9, -9);
    test(S(L"abcdefghij"), 0, 0, L"abcdefghij", 10, -10);
    test(S(L"abcdefghij"), 0, 0, L"abcdefghijklmnopqrst", 0, 0);
    test(S(L"abcdefghij"), 0, 0, L"abcdefghijklmnopqrst", 1, -1);
    test(S(L"abcdefghij"), 0, 0, L"abcdefghijklmnopqrst", 10, -10);
    test(S(L"abcdefghij"), 0, 0, L"abcdefghijklmnopqrst", 19, -19);
    test(S(L"abcdefghij"), 0, 0, L"abcdefghijklmnopqrst", 20, -20);
    test(S(L"abcdefghij"), 0, 1, L"", 0, 1);
    test(S(L"abcdefghij"), 0, 1, L"abcde", 0, 1);
    test(S(L"abcdefghij"), 0, 1, L"abcde", 1, 0);
    test(S(L"abcdefghij"), 0, 1, L"abcde", 2, -1);
    test(S(L"abcdefghij"), 0, 1, L"abcde", 4, -3);
    test(S(L"abcdefghij"), 0, 1, L"abcde", 5, -4);
    test(S(L"abcdefghij"), 0, 1, L"abcdefghij", 0, 1);
    test(S(L"abcdefghij"), 0, 1, L"abcdefghij", 1, 0);
    test(S(L"abcdefghij"), 0, 1, L"abcdefghij", 5, -4);
    test(S(L"abcdefghij"), 0, 1, L"abcdefghij", 9, -8);
    test(S(L"abcdefghij"), 0, 1, L"abcdefghij", 10, -9);
    test(S(L"abcdefghij"), 0, 1, L"abcdefghijklmnopqrst", 0, 1);
    test(S(L"abcdefghij"), 0, 1, L"abcdefghijklmnopqrst", 1, 0);
    test(S(L"abcdefghij"), 0, 1, L"abcdefghijklmnopqrst", 10, -9);
    test(S(L"abcdefghij"), 0, 1, L"abcdefghijklmnopqrst", 19, -18);
    test(S(L"abcdefghij"), 0, 1, L"abcdefghijklmnopqrst", 20, -19);
    test(S(L"abcdefghij"), 0, 5, L"", 0, 5);
    test(S(L"abcdefghij"), 0, 5, L"abcde", 0, 5);
    test(S(L"abcdefghij"), 0, 5, L"abcde", 1, 4);
    test(S(L"abcdefghij"), 0, 5, L"abcde", 2, 3);
    test(S(L"abcdefghij"), 0, 5, L"abcde", 4, 1);
    test(S(L"abcdefghij"), 0, 5, L"abcde", 5, 0);
    test(S(L"abcdefghij"), 0, 5, L"abcdefghij", 0, 5);
    test(S(L"abcdefghij"), 0, 5, L"abcdefghij", 1, 4);
    test(S(L"abcdefghij"), 0, 5, L"abcdefghij", 5, 0);
    test(S(L"abcdefghij"), 0, 5, L"abcdefghij", 9, -4);
    test(S(L"abcdefghij"), 0, 5, L"abcdefghij", 10, -5);
    test(S(L"abcdefghij"), 0, 5, L"abcdefghijklmnopqrst", 0, 5);
    test(S(L"abcdefghij"), 0, 5, L"abcdefghijklmnopqrst", 1, 4);
    test(S(L"abcdefghij"), 0, 5, L"abcdefghijklmnopqrst", 10, -5);
    test(S(L"abcdefghij"), 0, 5, L"abcdefghijklmnopqrst", 19, -14);
    test(S(L"abcdefghij"), 0, 5, L"abcdefghijklmnopqrst", 20, -15);
    test(S(L"abcdefghij"), 0, 9, L"", 0, 9);
    test(S(L"abcdefghij"), 0, 9, L"abcde", 0, 9);
    test(S(L"abcdefghij"), 0, 9, L"abcde", 1, 8);
    test(S(L"abcdefghij"), 0, 9, L"abcde", 2, 7);
    test(S(L"abcdefghij"), 0, 9, L"abcde", 4, 5);
    test(S(L"abcdefghij"), 0, 9, L"abcde", 5, 4);
    test(S(L"abcdefghij"), 0, 9, L"abcdefghij", 0, 9);
    test(S(L"abcdefghij"), 0, 9, L"abcdefghij", 1, 8);
    test(S(L"abcdefghij"), 0, 9, L"abcdefghij", 5, 4);
    test(S(L"abcdefghij"), 0, 9, L"abcdefghij", 9, 0);
    test(S(L"abcdefghij"), 0, 9, L"abcdefghij", 10, -1);
    test(S(L"abcdefghij"), 0, 9, L"abcdefghijklmnopqrst", 0, 9);
    test(S(L"abcdefghij"), 0, 9, L"abcdefghijklmnopqrst", 1, 8);
    test(S(L"abcdefghij"), 0, 9, L"abcdefghijklmnopqrst", 10, -1);
    test(S(L"abcdefghij"), 0, 9, L"abcdefghijklmnopqrst", 19, -10);
    test(S(L"abcdefghij"), 0, 9, L"abcdefghijklmnopqrst", 20, -11);
    test(S(L"abcdefghij"), 0, 10, L"", 0, 10);
    test(S(L"abcdefghij"), 0, 10, L"abcde", 0, 10);
    test(S(L"abcdefghij"), 0, 10, L"abcde", 1, 9);
    test(S(L"abcdefghij"), 0, 10, L"abcde", 2, 8);
    test(S(L"abcdefghij"), 0, 10, L"abcde", 4, 6);
    test(S(L"abcdefghij"), 0, 10, L"abcde", 5, 5);
    test(S(L"abcdefghij"), 0, 10, L"abcdefghij", 0, 10);
    test(S(L"abcdefghij"), 0, 10, L"abcdefghij", 1, 9);
    test(S(L"abcdefghij"), 0, 10, L"abcdefghij", 5, 5);
    test(S(L"abcdefghij"), 0, 10, L"abcdefghij", 9, 1);
    test(S(L"abcdefghij"), 0, 10, L"abcdefghij", 10, 0);
    test(S(L"abcdefghij"), 0, 10, L"abcdefghijklmnopqrst", 0, 10);
    test(S(L"abcdefghij"), 0, 10, L"abcdefghijklmnopqrst", 1, 9);
    test(S(L"abcdefghij"), 0, 10, L"abcdefghijklmnopqrst", 10, 0);
    test(S(L"abcdefghij"), 0, 10, L"abcdefghijklmnopqrst", 19, -9);
    test(S(L"abcdefghij"), 0, 10, L"abcdefghijklmnopqrst", 20, -10);
    test(S(L"abcdefghij"), 0, 11, L"", 0, 10);
    test(S(L"abcdefghij"), 0, 11, L"abcde", 0, 10);
    test(S(L"abcdefghij"), 0, 11, L"abcde", 1, 9);
    test(S(L"abcdefghij"), 0, 11, L"abcde", 2, 8);
}

template <class S>
void test5()
{
    test(S(L"abcdefghij"), 0, 11, L"abcde", 4, 6);
    test(S(L"abcdefghij"), 0, 11, L"abcde", 5, 5);
    test(S(L"abcdefghij"), 0, 11, L"abcdefghij", 0, 10);
    test(S(L"abcdefghij"), 0, 11, L"abcdefghij", 1, 9);
    test(S(L"abcdefghij"), 0, 11, L"abcdefghij", 5, 5);
    test(S(L"abcdefghij"), 0, 11, L"abcdefghij", 9, 1);
    test(S(L"abcdefghij"), 0, 11, L"abcdefghij", 10, 0);
    test(S(L"abcdefghij"), 0, 11, L"abcdefghijklmnopqrst", 0, 10);
    test(S(L"abcdefghij"), 0, 11, L"abcdefghijklmnopqrst", 1, 9);
    test(S(L"abcdefghij"), 0, 11, L"abcdefghijklmnopqrst", 10, 0);
    test(S(L"abcdefghij"), 0, 11, L"abcdefghijklmnopqrst", 19, -9);
    test(S(L"abcdefghij"), 0, 11, L"abcdefghijklmnopqrst", 20, -10);
    test(S(L"abcdefghij"), 1, 0, L"", 0, 0);
    test(S(L"abcdefghij"), 1, 0, L"abcde", 0, 0);
    test(S(L"abcdefghij"), 1, 0, L"abcde", 1, -1);
    test(S(L"abcdefghij"), 1, 0, L"abcde", 2, -2);
    test(S(L"abcdefghij"), 1, 0, L"abcde", 4, -4);
    test(S(L"abcdefghij"), 1, 0, L"abcde", 5, -5);
    test(S(L"abcdefghij"), 1, 0, L"abcdefghij", 0, 0);
    test(S(L"abcdefghij"), 1, 0, L"abcdefghij", 1, -1);
    test(S(L"abcdefghij"), 1, 0, L"abcdefghij", 5, -5);
    test(S(L"abcdefghij"), 1, 0, L"abcdefghij", 9, -9);
    test(S(L"abcdefghij"), 1, 0, L"abcdefghij", 10, -10);
    test(S(L"abcdefghij"), 1, 0, L"abcdefghijklmnopqrst", 0, 0);
    test(S(L"abcdefghij"), 1, 0, L"abcdefghijklmnopqrst", 1, -1);
    test(S(L"abcdefghij"), 1, 0, L"abcdefghijklmnopqrst", 10, -10);
    test(S(L"abcdefghij"), 1, 0, L"abcdefghijklmnopqrst", 19, -19);
    test(S(L"abcdefghij"), 1, 0, L"abcdefghijklmnopqrst", 20, -20);
    test(S(L"abcdefghij"), 1, 1, L"", 0, 1);
    test(S(L"abcdefghij"), 1, 1, L"abcde", 0, 1);
    test(S(L"abcdefghij"), 1, 1, L"abcde", 1, 1);
    test(S(L"abcdefghij"), 1, 1, L"abcde", 2, 1);
    test(S(L"abcdefghij"), 1, 1, L"abcde", 4, 1);
    test(S(L"abcdefghij"), 1, 1, L"abcde", 5, 1);
    test(S(L"abcdefghij"), 1, 1, L"abcdefghij", 0, 1);
    test(S(L"abcdefghij"), 1, 1, L"abcdefghij", 1, 1);
    test(S(L"abcdefghij"), 1, 1, L"abcdefghij", 5, 1);
    test(S(L"abcdefghij"), 1, 1, L"abcdefghij", 9, 1);
    test(S(L"abcdefghij"), 1, 1, L"abcdefghij", 10, 1);
    test(S(L"abcdefghij"), 1, 1, L"abcdefghijklmnopqrst", 0, 1);
    test(S(L"abcdefghij"), 1, 1, L"abcdefghijklmnopqrst", 1, 1);
    test(S(L"abcdefghij"), 1, 1, L"abcdefghijklmnopqrst", 10, 1);
    test(S(L"abcdefghij"), 1, 1, L"abcdefghijklmnopqrst", 19, 1);
    test(S(L"abcdefghij"), 1, 1, L"abcdefghijklmnopqrst", 20, 1);
    test(S(L"abcdefghij"), 1, 4, L"", 0, 4);
    test(S(L"abcdefghij"), 1, 4, L"abcde", 0, 4);
    test(S(L"abcdefghij"), 1, 4, L"abcde", 1, 1);
    test(S(L"abcdefghij"), 1, 4, L"abcde", 2, 1);
    test(S(L"abcdefghij"), 1, 4, L"abcde", 4, 1);
    test(S(L"abcdefghij"), 1, 4, L"abcde", 5, 1);
    test(S(L"abcdefghij"), 1, 4, L"abcdefghij", 0, 4);
    test(S(L"abcdefghij"), 1, 4, L"abcdefghij", 1, 1);
    test(S(L"abcdefghij"), 1, 4, L"abcdefghij", 5, 1);
    test(S(L"abcdefghij"), 1, 4, L"abcdefghij", 9, 1);
    test(S(L"abcdefghij"), 1, 4, L"abcdefghij", 10, 1);
    test(S(L"abcdefghij"), 1, 4, L"abcdefghijklmnopqrst", 0, 4);
    test(S(L"abcdefghij"), 1, 4, L"abcdefghijklmnopqrst", 1, 1);
    test(S(L"abcdefghij"), 1, 4, L"abcdefghijklmnopqrst", 10, 1);
    test(S(L"abcdefghij"), 1, 4, L"abcdefghijklmnopqrst", 19, 1);
    test(S(L"abcdefghij"), 1, 4, L"abcdefghijklmnopqrst", 20, 1);
    test(S(L"abcdefghij"), 1, 8, L"", 0, 8);
    test(S(L"abcdefghij"), 1, 8, L"abcde", 0, 8);
    test(S(L"abcdefghij"), 1, 8, L"abcde", 1, 1);
    test(S(L"abcdefghij"), 1, 8, L"abcde", 2, 1);
    test(S(L"abcdefghij"), 1, 8, L"abcde", 4, 1);
    test(S(L"abcdefghij"), 1, 8, L"abcde", 5, 1);
    test(S(L"abcdefghij"), 1, 8, L"abcdefghij", 0, 8);
    test(S(L"abcdefghij"), 1, 8, L"abcdefghij", 1, 1);
    test(S(L"abcdefghij"), 1, 8, L"abcdefghij", 5, 1);
    test(S(L"abcdefghij"), 1, 8, L"abcdefghij", 9, 1);
    test(S(L"abcdefghij"), 1, 8, L"abcdefghij", 10, 1);
    test(S(L"abcdefghij"), 1, 8, L"abcdefghijklmnopqrst", 0, 8);
    test(S(L"abcdefghij"), 1, 8, L"abcdefghijklmnopqrst", 1, 1);
    test(S(L"abcdefghij"), 1, 8, L"abcdefghijklmnopqrst", 10, 1);
    test(S(L"abcdefghij"), 1, 8, L"abcdefghijklmnopqrst", 19, 1);
    test(S(L"abcdefghij"), 1, 8, L"abcdefghijklmnopqrst", 20, 1);
    test(S(L"abcdefghij"), 1, 9, L"", 0, 9);
    test(S(L"abcdefghij"), 1, 9, L"abcde", 0, 9);
    test(S(L"abcdefghij"), 1, 9, L"abcde", 1, 1);
    test(S(L"abcdefghij"), 1, 9, L"abcde", 2, 1);
    test(S(L"abcdefghij"), 1, 9, L"abcde", 4, 1);
    test(S(L"abcdefghij"), 1, 9, L"abcde", 5, 1);
    test(S(L"abcdefghij"), 1, 9, L"abcdefghij", 0, 9);
    test(S(L"abcdefghij"), 1, 9, L"abcdefghij", 1, 1);
    test(S(L"abcdefghij"), 1, 9, L"abcdefghij", 5, 1);
    test(S(L"abcdefghij"), 1, 9, L"abcdefghij", 9, 1);
    test(S(L"abcdefghij"), 1, 9, L"abcdefghij", 10, 1);
    test(S(L"abcdefghij"), 1, 9, L"abcdefghijklmnopqrst", 0, 9);
    test(S(L"abcdefghij"), 1, 9, L"abcdefghijklmnopqrst", 1, 1);
    test(S(L"abcdefghij"), 1, 9, L"abcdefghijklmnopqrst", 10, 1);
    test(S(L"abcdefghij"), 1, 9, L"abcdefghijklmnopqrst", 19, 1);
    test(S(L"abcdefghij"), 1, 9, L"abcdefghijklmnopqrst", 20, 1);
    test(S(L"abcdefghij"), 1, 10, L"", 0, 9);
    test(S(L"abcdefghij"), 1, 10, L"abcde", 0, 9);
    test(S(L"abcdefghij"), 1, 10, L"abcde", 1, 1);
    test(S(L"abcdefghij"), 1, 10, L"abcde", 2, 1);
    test(S(L"abcdefghij"), 1, 10, L"abcde", 4, 1);
    test(S(L"abcdefghij"), 1, 10, L"abcde", 5, 1);
    test(S(L"abcdefghij"), 1, 10, L"abcdefghij", 0, 9);
    test(S(L"abcdefghij"), 1, 10, L"abcdefghij", 1, 1);
}

template <class S>
void test6()
{
    test(S(L"abcdefghij"), 1, 10, L"abcdefghij", 5, 1);
    test(S(L"abcdefghij"), 1, 10, L"abcdefghij", 9, 1);
    test(S(L"abcdefghij"), 1, 10, L"abcdefghij", 10, 1);
    test(S(L"abcdefghij"), 1, 10, L"abcdefghijklmnopqrst", 0, 9);
    test(S(L"abcdefghij"), 1, 10, L"abcdefghijklmnopqrst", 1, 1);
    test(S(L"abcdefghij"), 1, 10, L"abcdefghijklmnopqrst", 10, 1);
    test(S(L"abcdefghij"), 1, 10, L"abcdefghijklmnopqrst", 19, 1);
    test(S(L"abcdefghij"), 1, 10, L"abcdefghijklmnopqrst", 20, 1);
    test(S(L"abcdefghij"), 5, 0, L"", 0, 0);
    test(S(L"abcdefghij"), 5, 0, L"abcde", 0, 0);
    test(S(L"abcdefghij"), 5, 0, L"abcde", 1, -1);
    test(S(L"abcdefghij"), 5, 0, L"abcde", 2, -2);
    test(S(L"abcdefghij"), 5, 0, L"abcde", 4, -4);
    test(S(L"abcdefghij"), 5, 0, L"abcde", 5, -5);
    test(S(L"abcdefghij"), 5, 0, L"abcdefghij", 0, 0);
    test(S(L"abcdefghij"), 5, 0, L"abcdefghij", 1, -1);
    test(S(L"abcdefghij"), 5, 0, L"abcdefghij", 5, -5);
    test(S(L"abcdefghij"), 5, 0, L"abcdefghij", 9, -9);
    test(S(L"abcdefghij"), 5, 0, L"abcdefghij", 10, -10);
    test(S(L"abcdefghij"), 5, 0, L"abcdefghijklmnopqrst", 0, 0);
    test(S(L"abcdefghij"), 5, 0, L"abcdefghijklmnopqrst", 1, -1);
    test(S(L"abcdefghij"), 5, 0, L"abcdefghijklmnopqrst", 10, -10);
    test(S(L"abcdefghij"), 5, 0, L"abcdefghijklmnopqrst", 19, -19);
    test(S(L"abcdefghij"), 5, 0, L"abcdefghijklmnopqrst", 20, -20);
    test(S(L"abcdefghij"), 5, 1, L"", 0, 1);
    test(S(L"abcdefghij"), 5, 1, L"abcde", 0, 1);
    test(S(L"abcdefghij"), 5, 1, L"abcde", 1, 5);
    test(S(L"abcdefghij"), 5, 1, L"abcde", 2, 5);
    test(S(L"abcdefghij"), 5, 1, L"abcde", 4, 5);
    test(S(L"abcdefghij"), 5, 1, L"abcde", 5, 5);
    test(S(L"abcdefghij"), 5, 1, L"abcdefghij", 0, 1);
    test(S(L"abcdefghij"), 5, 1, L"abcdefghij", 1, 5);
    test(S(L"abcdefghij"), 5, 1, L"abcdefghij", 5, 5);
    test(S(L"abcdefghij"), 5, 1, L"abcdefghij", 9, 5);
    test(S(L"abcdefghij"), 5, 1, L"abcdefghij", 10, 5);
    test(S(L"abcdefghij"), 5, 1, L"abcdefghijklmnopqrst", 0, 1);
    test(S(L"abcdefghij"), 5, 1, L"abcdefghijklmnopqrst", 1, 5);
    test(S(L"abcdefghij"), 5, 1, L"abcdefghijklmnopqrst", 10, 5);
    test(S(L"abcdefghij"), 5, 1, L"abcdefghijklmnopqrst", 19, 5);
    test(S(L"abcdefghij"), 5, 1, L"abcdefghijklmnopqrst", 20, 5);
    test(S(L"abcdefghij"), 5, 2, L"", 0, 2);
    test(S(L"abcdefghij"), 5, 2, L"abcde", 0, 2);
    test(S(L"abcdefghij"), 5, 2, L"abcde", 1, 5);
    test(S(L"abcdefghij"), 5, 2, L"abcde", 2, 5);
    test(S(L"abcdefghij"), 5, 2, L"abcde", 4, 5);
    test(S(L"abcdefghij"), 5, 2, L"abcde", 5, 5);
    test(S(L"abcdefghij"), 5, 2, L"abcdefghij", 0, 2);
    test(S(L"abcdefghij"), 5, 2, L"abcdefghij", 1, 5);
    test(S(L"abcdefghij"), 5, 2, L"abcdefghij", 5, 5);
    test(S(L"abcdefghij"), 5, 2, L"abcdefghij", 9, 5);
    test(S(L"abcdefghij"), 5, 2, L"abcdefghij", 10, 5);
    test(S(L"abcdefghij"), 5, 2, L"abcdefghijklmnopqrst", 0, 2);
    test(S(L"abcdefghij"), 5, 2, L"abcdefghijklmnopqrst", 1, 5);
    test(S(L"abcdefghij"), 5, 2, L"abcdefghijklmnopqrst", 10, 5);
    test(S(L"abcdefghij"), 5, 2, L"abcdefghijklmnopqrst", 19, 5);
    test(S(L"abcdefghij"), 5, 2, L"abcdefghijklmnopqrst", 20, 5);
    test(S(L"abcdefghij"), 5, 4, L"", 0, 4);
    test(S(L"abcdefghij"), 5, 4, L"abcde", 0, 4);
    test(S(L"abcdefghij"), 5, 4, L"abcde", 1, 5);
    test(S(L"abcdefghij"), 5, 4, L"abcde", 2, 5);
    test(S(L"abcdefghij"), 5, 4, L"abcde", 4, 5);
    test(S(L"abcdefghij"), 5, 4, L"abcde", 5, 5);
    test(S(L"abcdefghij"), 5, 4, L"abcdefghij", 0, 4);
    test(S(L"abcdefghij"), 5, 4, L"abcdefghij", 1, 5);
    test(S(L"abcdefghij"), 5, 4, L"abcdefghij", 5, 5);
    test(S(L"abcdefghij"), 5, 4, L"abcdefghij", 9, 5);
    test(S(L"abcdefghij"), 5, 4, L"abcdefghij", 10, 5);
    test(S(L"abcdefghij"), 5, 4, L"abcdefghijklmnopqrst", 0, 4);
    test(S(L"abcdefghij"), 5, 4, L"abcdefghijklmnopqrst", 1, 5);
    test(S(L"abcdefghij"), 5, 4, L"abcdefghijklmnopqrst", 10, 5);
    test(S(L"abcdefghij"), 5, 4, L"abcdefghijklmnopqrst", 19, 5);
    test(S(L"abcdefghij"), 5, 4, L"abcdefghijklmnopqrst", 20, 5);
    test(S(L"abcdefghij"), 5, 5, L"", 0, 5);
    test(S(L"abcdefghij"), 5, 5, L"abcde", 0, 5);
    test(S(L"abcdefghij"), 5, 5, L"abcde", 1, 5);
    test(S(L"abcdefghij"), 5, 5, L"abcde", 2, 5);
    test(S(L"abcdefghij"), 5, 5, L"abcde", 4, 5);
    test(S(L"abcdefghij"), 5, 5, L"abcde", 5, 5);
    test(S(L"abcdefghij"), 5, 5, L"abcdefghij", 0, 5);
    test(S(L"abcdefghij"), 5, 5, L"abcdefghij", 1, 5);
    test(S(L"abcdefghij"), 5, 5, L"abcdefghij", 5, 5);
    test(S(L"abcdefghij"), 5, 5, L"abcdefghij", 9, 5);
    test(S(L"abcdefghij"), 5, 5, L"abcdefghij", 10, 5);
    test(S(L"abcdefghij"), 5, 5, L"abcdefghijklmnopqrst", 0, 5);
    test(S(L"abcdefghij"), 5, 5, L"abcdefghijklmnopqrst", 1, 5);
    test(S(L"abcdefghij"), 5, 5, L"abcdefghijklmnopqrst", 10, 5);
    test(S(L"abcdefghij"), 5, 5, L"abcdefghijklmnopqrst", 19, 5);
    test(S(L"abcdefghij"), 5, 5, L"abcdefghijklmnopqrst", 20, 5);
    test(S(L"abcdefghij"), 5, 6, L"", 0, 5);
    test(S(L"abcdefghij"), 5, 6, L"abcde", 0, 5);
    test(S(L"abcdefghij"), 5, 6, L"abcde", 1, 5);
    test(S(L"abcdefghij"), 5, 6, L"abcde", 2, 5);
    test(S(L"abcdefghij"), 5, 6, L"abcde", 4, 5);
    test(S(L"abcdefghij"), 5, 6, L"abcde", 5, 5);
    test(S(L"abcdefghij"), 5, 6, L"abcdefghij", 0, 5);
    test(S(L"abcdefghij"), 5, 6, L"abcdefghij", 1, 5);
    test(S(L"abcdefghij"), 5, 6, L"abcdefghij", 5, 5);
    test(S(L"abcdefghij"), 5, 6, L"abcdefghij", 9, 5);
    test(S(L"abcdefghij"), 5, 6, L"abcdefghij", 10, 5);
    test(S(L"abcdefghij"), 5, 6, L"abcdefghijklmnopqrst", 0, 5);
}

template <class S>
void test7()
{
    test(S(L"abcdefghij"), 5, 6, L"abcdefghijklmnopqrst", 1, 5);
    test(S(L"abcdefghij"), 5, 6, L"abcdefghijklmnopqrst", 10, 5);
    test(S(L"abcdefghij"), 5, 6, L"abcdefghijklmnopqrst", 19, 5);
    test(S(L"abcdefghij"), 5, 6, L"abcdefghijklmnopqrst", 20, 5);
    test(S(L"abcdefghij"), 9, 0, L"", 0, 0);
    test(S(L"abcdefghij"), 9, 0, L"abcde", 0, 0);
    test(S(L"abcdefghij"), 9, 0, L"abcde", 1, -1);
    test(S(L"abcdefghij"), 9, 0, L"abcde", 2, -2);
    test(S(L"abcdefghij"), 9, 0, L"abcde", 4, -4);
    test(S(L"abcdefghij"), 9, 0, L"abcde", 5, -5);
    test(S(L"abcdefghij"), 9, 0, L"abcdefghij", 0, 0);
    test(S(L"abcdefghij"), 9, 0, L"abcdefghij", 1, -1);
    test(S(L"abcdefghij"), 9, 0, L"abcdefghij", 5, -5);
    test(S(L"abcdefghij"), 9, 0, L"abcdefghij", 9, -9);
    test(S(L"abcdefghij"), 9, 0, L"abcdefghij", 10, -10);
    test(S(L"abcdefghij"), 9, 0, L"abcdefghijklmnopqrst", 0, 0);
    test(S(L"abcdefghij"), 9, 0, L"abcdefghijklmnopqrst", 1, -1);
    test(S(L"abcdefghij"), 9, 0, L"abcdefghijklmnopqrst", 10, -10);
    test(S(L"abcdefghij"), 9, 0, L"abcdefghijklmnopqrst", 19, -19);
    test(S(L"abcdefghij"), 9, 0, L"abcdefghijklmnopqrst", 20, -20);
    test(S(L"abcdefghij"), 9, 1, L"", 0, 1);
    test(S(L"abcdefghij"), 9, 1, L"abcde", 0, 1);
    test(S(L"abcdefghij"), 9, 1, L"abcde", 1, 9);
    test(S(L"abcdefghij"), 9, 1, L"abcde", 2, 9);
    test(S(L"abcdefghij"), 9, 1, L"abcde", 4, 9);
    test(S(L"abcdefghij"), 9, 1, L"abcde", 5, 9);
    test(S(L"abcdefghij"), 9, 1, L"abcdefghij", 0, 1);
    test(S(L"abcdefghij"), 9, 1, L"abcdefghij", 1, 9);
    test(S(L"abcdefghij"), 9, 1, L"abcdefghij", 5, 9);
    test(S(L"abcdefghij"), 9, 1, L"abcdefghij", 9, 9);
    test(S(L"abcdefghij"), 9, 1, L"abcdefghij", 10, 9);
    test(S(L"abcdefghij"), 9, 1, L"abcdefghijklmnopqrst", 0, 1);
    test(S(L"abcdefghij"), 9, 1, L"abcdefghijklmnopqrst", 1, 9);
    test(S(L"abcdefghij"), 9, 1, L"abcdefghijklmnopqrst", 10, 9);
    test(S(L"abcdefghij"), 9, 1, L"abcdefghijklmnopqrst", 19, 9);
    test(S(L"abcdefghij"), 9, 1, L"abcdefghijklmnopqrst", 20, 9);
    test(S(L"abcdefghij"), 9, 2, L"", 0, 1);
    test(S(L"abcdefghij"), 9, 2, L"abcde", 0, 1);
    test(S(L"abcdefghij"), 9, 2, L"abcde", 1, 9);
    test(S(L"abcdefghij"), 9, 2, L"abcde", 2, 9);
    test(S(L"abcdefghij"), 9, 2, L"abcde", 4, 9);
    test(S(L"abcdefghij"), 9, 2, L"abcde", 5, 9);
    test(S(L"abcdefghij"), 9, 2, L"abcdefghij", 0, 1);
    test(S(L"abcdefghij"), 9, 2, L"abcdefghij", 1, 9);
    test(S(L"abcdefghij"), 9, 2, L"abcdefghij", 5, 9);
    test(S(L"abcdefghij"), 9, 2, L"abcdefghij", 9, 9);
    test(S(L"abcdefghij"), 9, 2, L"abcdefghij", 10, 9);
    test(S(L"abcdefghij"), 9, 2, L"abcdefghijklmnopqrst", 0, 1);
    test(S(L"abcdefghij"), 9, 2, L"abcdefghijklmnopqrst", 1, 9);
    test(S(L"abcdefghij"), 9, 2, L"abcdefghijklmnopqrst", 10, 9);
    test(S(L"abcdefghij"), 9, 2, L"abcdefghijklmnopqrst", 19, 9);
    test(S(L"abcdefghij"), 9, 2, L"abcdefghijklmnopqrst", 20, 9);
    test(S(L"abcdefghij"), 10, 0, L"", 0, 0);
    test(S(L"abcdefghij"), 10, 0, L"abcde", 0, 0);
    test(S(L"abcdefghij"), 10, 0, L"abcde", 1, -1);
    test(S(L"abcdefghij"), 10, 0, L"abcde", 2, -2);
    test(S(L"abcdefghij"), 10, 0, L"abcde", 4, -4);
    test(S(L"abcdefghij"), 10, 0, L"abcde", 5, -5);
    test(S(L"abcdefghij"), 10, 0, L"abcdefghij", 0, 0);
    test(S(L"abcdefghij"), 10, 0, L"abcdefghij", 1, -1);
    test(S(L"abcdefghij"), 10, 0, L"abcdefghij", 5, -5);
    test(S(L"abcdefghij"), 10, 0, L"abcdefghij", 9, -9);
    test(S(L"abcdefghij"), 10, 0, L"abcdefghij", 10, -10);
    test(S(L"abcdefghij"), 10, 0, L"abcdefghijklmnopqrst", 0, 0);
    test(S(L"abcdefghij"), 10, 0, L"abcdefghijklmnopqrst", 1, -1);
    test(S(L"abcdefghij"), 10, 0, L"abcdefghijklmnopqrst", 10, -10);
    test(S(L"abcdefghij"), 10, 0, L"abcdefghijklmnopqrst", 19, -19);
    test(S(L"abcdefghij"), 10, 0, L"abcdefghijklmnopqrst", 20, -20);
    test(S(L"abcdefghij"), 10, 1, L"", 0, 0);
    test(S(L"abcdefghij"), 10, 1, L"abcde", 0, 0);
    test(S(L"abcdefghij"), 10, 1, L"abcde", 1, -1);
    test(S(L"abcdefghij"), 10, 1, L"abcde", 2, -2);
    test(S(L"abcdefghij"), 10, 1, L"abcde", 4, -4);
    test(S(L"abcdefghij"), 10, 1, L"abcde", 5, -5);
    test(S(L"abcdefghij"), 10, 1, L"abcdefghij", 0, 0);
    test(S(L"abcdefghij"), 10, 1, L"abcdefghij", 1, -1);
    test(S(L"abcdefghij"), 10, 1, L"abcdefghij", 5, -5);
    test(S(L"abcdefghij"), 10, 1, L"abcdefghij", 9, -9);
    test(S(L"abcdefghij"), 10, 1, L"abcdefghij", 10, -10);
    test(S(L"abcdefghij"), 10, 1, L"abcdefghijklmnopqrst", 0, 0);
    test(S(L"abcdefghij"), 10, 1, L"abcdefghijklmnopqrst", 1, -1);
    test(S(L"abcdefghij"), 10, 1, L"abcdefghijklmnopqrst", 10, -10);
    test(S(L"abcdefghij"), 10, 1, L"abcdefghijklmnopqrst", 19, -19);
    test(S(L"abcdefghij"), 10, 1, L"abcdefghijklmnopqrst", 20, -20);
    test(S(L"abcdefghij"), 11, 0, L"", 0, 0);
    test(S(L"abcdefghij"), 11, 0, L"abcde", 0, 0);
    test(S(L"abcdefghij"), 11, 0, L"abcde", 1, 0);
    test(S(L"abcdefghij"), 11, 0, L"abcde", 2, 0);
    test(S(L"abcdefghij"), 11, 0, L"abcde", 4, 0);
    test(S(L"abcdefghij"), 11, 0, L"abcde", 5, 0);
    test(S(L"abcdefghij"), 11, 0, L"abcdefghij", 0, 0);
    test(S(L"abcdefghij"), 11, 0, L"abcdefghij", 1, 0);
    test(S(L"abcdefghij"), 11, 0, L"abcdefghij", 5, 0);
    test(S(L"abcdefghij"), 11, 0, L"abcdefghij", 9, 0);
    test(S(L"abcdefghij"), 11, 0, L"abcdefghij", 10, 0);
    test(S(L"abcdefghij"), 11, 0, L"abcdefghijklmnopqrst", 0, 0);
    test(S(L"abcdefghij"), 11, 0, L"abcdefghijklmnopqrst", 1, 0);
    test(S(L"abcdefghij"), 11, 0, L"abcdefghijklmnopqrst", 10, 0);
    test(S(L"abcdefghij"), 11, 0, L"abcdefghijklmnopqrst", 19, 0);
    test(S(L"abcdefghij"), 11, 0, L"abcdefghijklmnopqrst", 20, 0);
}

template <class S>
void test8()
{
    test(S(L"abcdefghijklmnopqrst"), 0, 0, L"", 0, 0);
    test(S(L"abcdefghijklmnopqrst"), 0, 0, L"abcde", 0, 0);
    test(S(L"abcdefghijklmnopqrst"), 0, 0, L"abcde", 1, -1);
    test(S(L"abcdefghijklmnopqrst"), 0, 0, L"abcde", 2, -2);
    test(S(L"abcdefghijklmnopqrst"), 0, 0, L"abcde", 4, -4);
    test(S(L"abcdefghijklmnopqrst"), 0, 0, L"abcde", 5, -5);
    test(S(L"abcdefghijklmnopqrst"), 0, 0, L"abcdefghij", 0, 0);
    test(S(L"abcdefghijklmnopqrst"), 0, 0, L"abcdefghij", 1, -1);
    test(S(L"abcdefghijklmnopqrst"), 0, 0, L"abcdefghij", 5, -5);
    test(S(L"abcdefghijklmnopqrst"), 0, 0, L"abcdefghij", 9, -9);
    test(S(L"abcdefghijklmnopqrst"), 0, 0, L"abcdefghij", 10, -10);
    test(S(L"abcdefghijklmnopqrst"), 0, 0, L"abcdefghijklmnopqrst", 0, 0);
    test(S(L"abcdefghijklmnopqrst"), 0, 0, L"abcdefghijklmnopqrst", 1, -1);
    test(S(L"abcdefghijklmnopqrst"), 0, 0, L"abcdefghijklmnopqrst", 10, -10);
    test(S(L"abcdefghijklmnopqrst"), 0, 0, L"abcdefghijklmnopqrst", 19, -19);
    test(S(L"abcdefghijklmnopqrst"), 0, 0, L"abcdefghijklmnopqrst", 20, -20);
    test(S(L"abcdefghijklmnopqrst"), 0, 1, L"", 0, 1);
    test(S(L"abcdefghijklmnopqrst"), 0, 1, L"abcde", 0, 1);
    test(S(L"abcdefghijklmnopqrst"), 0, 1, L"abcde", 1, 0);
    test(S(L"abcdefghijklmnopqrst"), 0, 1, L"abcde", 2, -1);
    test(S(L"abcdefghijklmnopqrst"), 0, 1, L"abcde", 4, -3);
    test(S(L"abcdefghijklmnopqrst"), 0, 1, L"abcde", 5, -4);
    test(S(L"abcdefghijklmnopqrst"), 0, 1, L"abcdefghij", 0, 1);
    test(S(L"abcdefghijklmnopqrst"), 0, 1, L"abcdefghij", 1, 0);
    test(S(L"abcdefghijklmnopqrst"), 0, 1, L"abcdefghij", 5, -4);
    test(S(L"abcdefghijklmnopqrst"), 0, 1, L"abcdefghij", 9, -8);
    test(S(L"abcdefghijklmnopqrst"), 0, 1, L"abcdefghij", 10, -9);
    test(S(L"abcdefghijklmnopqrst"), 0, 1, L"abcdefghijklmnopqrst", 0, 1);
    test(S(L"abcdefghijklmnopqrst"), 0, 1, L"abcdefghijklmnopqrst", 1, 0);
    test(S(L"abcdefghijklmnopqrst"), 0, 1, L"abcdefghijklmnopqrst", 10, -9);
    test(S(L"abcdefghijklmnopqrst"), 0, 1, L"abcdefghijklmnopqrst", 19, -18);
    test(S(L"abcdefghijklmnopqrst"), 0, 1, L"abcdefghijklmnopqrst", 20, -19);
    test(S(L"abcdefghijklmnopqrst"), 0, 10, L"", 0, 10);
    test(S(L"abcdefghijklmnopqrst"), 0, 10, L"abcde", 0, 10);
    test(S(L"abcdefghijklmnopqrst"), 0, 10, L"abcde", 1, 9);
    test(S(L"abcdefghijklmnopqrst"), 0, 10, L"abcde", 2, 8);
    test(S(L"abcdefghijklmnopqrst"), 0, 10, L"abcde", 4, 6);
    test(S(L"abcdefghijklmnopqrst"), 0, 10, L"abcde", 5, 5);
    test(S(L"abcdefghijklmnopqrst"), 0, 10, L"abcdefghij", 0, 10);
    test(S(L"abcdefghijklmnopqrst"), 0, 10, L"abcdefghij", 1, 9);
    test(S(L"abcdefghijklmnopqrst"), 0, 10, L"abcdefghij", 5, 5);
    test(S(L"abcdefghijklmnopqrst"), 0, 10, L"abcdefghij", 9, 1);
    test(S(L"abcdefghijklmnopqrst"), 0, 10, L"abcdefghij", 10, 0);
    test(S(L"abcdefghijklmnopqrst"), 0, 10, L"abcdefghijklmnopqrst", 0, 10);
    test(S(L"abcdefghijklmnopqrst"), 0, 10, L"abcdefghijklmnopqrst", 1, 9);
    test(S(L"abcdefghijklmnopqrst"), 0, 10, L"abcdefghijklmnopqrst", 10, 0);
    test(S(L"abcdefghijklmnopqrst"), 0, 10, L"abcdefghijklmnopqrst", 19, -9);
    test(S(L"abcdefghijklmnopqrst"), 0, 10, L"abcdefghijklmnopqrst", 20, -10);
    test(S(L"abcdefghijklmnopqrst"), 0, 19, L"", 0, 19);
    test(S(L"abcdefghijklmnopqrst"), 0, 19, L"abcde", 0, 19);
    test(S(L"abcdefghijklmnopqrst"), 0, 19, L"abcde", 1, 18);
    test(S(L"abcdefghijklmnopqrst"), 0, 19, L"abcde", 2, 17);
    test(S(L"abcdefghijklmnopqrst"), 0, 19, L"abcde", 4, 15);
    test(S(L"abcdefghijklmnopqrst"), 0, 19, L"abcde", 5, 14);
    test(S(L"abcdefghijklmnopqrst"), 0, 19, L"abcdefghij", 0, 19);
    test(S(L"abcdefghijklmnopqrst"), 0, 19, L"abcdefghij", 1, 18);
    test(S(L"abcdefghijklmnopqrst"), 0, 19, L"abcdefghij", 5, 14);
    test(S(L"abcdefghijklmnopqrst"), 0, 19, L"abcdefghij", 9, 10);
    test(S(L"abcdefghijklmnopqrst"), 0, 19, L"abcdefghij", 10, 9);
    test(S(L"abcdefghijklmnopqrst"), 0, 19, L"abcdefghijklmnopqrst", 0, 19);
    test(S(L"abcdefghijklmnopqrst"), 0, 19, L"abcdefghijklmnopqrst", 1, 18);
    test(S(L"abcdefghijklmnopqrst"), 0, 19, L"abcdefghijklmnopqrst", 10, 9);
    test(S(L"abcdefghijklmnopqrst"), 0, 19, L"abcdefghijklmnopqrst", 19, 0);
    test(S(L"abcdefghijklmnopqrst"), 0, 19, L"abcdefghijklmnopqrst", 20, -1);
    test(S(L"abcdefghijklmnopqrst"), 0, 20, L"", 0, 20);
    test(S(L"abcdefghijklmnopqrst"), 0, 20, L"abcde", 0, 20);
    test(S(L"abcdefghijklmnopqrst"), 0, 20, L"abcde", 1, 19);
    test(S(L"abcdefghijklmnopqrst"), 0, 20, L"abcde", 2, 18);
    test(S(L"abcdefghijklmnopqrst"), 0, 20, L"abcde", 4, 16);
    test(S(L"abcdefghijklmnopqrst"), 0, 20, L"abcde", 5, 15);
    test(S(L"abcdefghijklmnopqrst"), 0, 20, L"abcdefghij", 0, 20);
    test(S(L"abcdefghijklmnopqrst"), 0, 20, L"abcdefghij", 1, 19);
    test(S(L"abcdefghijklmnopqrst"), 0, 20, L"abcdefghij", 5, 15);
    test(S(L"abcdefghijklmnopqrst"), 0, 20, L"abcdefghij", 9, 11);
    test(S(L"abcdefghijklmnopqrst"), 0, 20, L"abcdefghij", 10, 10);
    test(S(L"abcdefghijklmnopqrst"), 0, 20, L"abcdefghijklmnopqrst", 0, 20);
    test(S(L"abcdefghijklmnopqrst"), 0, 20, L"abcdefghijklmnopqrst", 1, 19);
    test(S(L"abcdefghijklmnopqrst"), 0, 20, L"abcdefghijklmnopqrst", 10, 10);
    test(S(L"abcdefghijklmnopqrst"), 0, 20, L"abcdefghijklmnopqrst", 19, 1);
    test(S(L"abcdefghijklmnopqrst"), 0, 20, L"abcdefghijklmnopqrst", 20, 0);
    test(S(L"abcdefghijklmnopqrst"), 0, 21, L"", 0, 20);
    test(S(L"abcdefghijklmnopqrst"), 0, 21, L"abcde", 0, 20);
    test(S(L"abcdefghijklmnopqrst"), 0, 21, L"abcde", 1, 19);
    test(S(L"abcdefghijklmnopqrst"), 0, 21, L"abcde", 2, 18);
    test(S(L"abcdefghijklmnopqrst"), 0, 21, L"abcde", 4, 16);
    test(S(L"abcdefghijklmnopqrst"), 0, 21, L"abcde", 5, 15);
    test(S(L"abcdefghijklmnopqrst"), 0, 21, L"abcdefghij", 0, 20);
    test(S(L"abcdefghijklmnopqrst"), 0, 21, L"abcdefghij", 1, 19);
    test(S(L"abcdefghijklmnopqrst"), 0, 21, L"abcdefghij", 5, 15);
    test(S(L"abcdefghijklmnopqrst"), 0, 21, L"abcdefghij", 9, 11);
    test(S(L"abcdefghijklmnopqrst"), 0, 21, L"abcdefghij", 10, 10);
    test(S(L"abcdefghijklmnopqrst"), 0, 21, L"abcdefghijklmnopqrst", 0, 20);
    test(S(L"abcdefghijklmnopqrst"), 0, 21, L"abcdefghijklmnopqrst", 1, 19);
    test(S(L"abcdefghijklmnopqrst"), 0, 21, L"abcdefghijklmnopqrst", 10, 10);
    test(S(L"abcdefghijklmnopqrst"), 0, 21, L"abcdefghijklmnopqrst", 19, 1);
    test(S(L"abcdefghijklmnopqrst"), 0, 21, L"abcdefghijklmnopqrst", 20, 0);
    test(S(L"abcdefghijklmnopqrst"), 1, 0, L"", 0, 0);
    test(S(L"abcdefghijklmnopqrst"), 1, 0, L"abcde", 0, 0);
    test(S(L"abcdefghijklmnopqrst"), 1, 0, L"abcde", 1, -1);
    test(S(L"abcdefghijklmnopqrst"), 1, 0, L"abcde", 2, -2);
}

template <class S>
void test9()
{
    test(S(L"abcdefghijklmnopqrst"), 1, 0, L"abcde", 4, -4);
    test(S(L"abcdefghijklmnopqrst"), 1, 0, L"abcde", 5, -5);
    test(S(L"abcdefghijklmnopqrst"), 1, 0, L"abcdefghij", 0, 0);
    test(S(L"abcdefghijklmnopqrst"), 1, 0, L"abcdefghij", 1, -1);
    test(S(L"abcdefghijklmnopqrst"), 1, 0, L"abcdefghij", 5, -5);
    test(S(L"abcdefghijklmnopqrst"), 1, 0, L"abcdefghij", 9, -9);
    test(S(L"abcdefghijklmnopqrst"), 1, 0, L"abcdefghij", 10, -10);
    test(S(L"abcdefghijklmnopqrst"), 1, 0, L"abcdefghijklmnopqrst", 0, 0);
    test(S(L"abcdefghijklmnopqrst"), 1, 0, L"abcdefghijklmnopqrst", 1, -1);
    test(S(L"abcdefghijklmnopqrst"), 1, 0, L"abcdefghijklmnopqrst", 10, -10);
    test(S(L"abcdefghijklmnopqrst"), 1, 0, L"abcdefghijklmnopqrst", 19, -19);
    test(S(L"abcdefghijklmnopqrst"), 1, 0, L"abcdefghijklmnopqrst", 20, -20);
    test(S(L"abcdefghijklmnopqrst"), 1, 1, L"", 0, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 1, L"abcde", 0, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 1, L"abcde", 1, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 1, L"abcde", 2, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 1, L"abcde", 4, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 1, L"abcde", 5, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 1, L"abcdefghij", 0, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 1, L"abcdefghij", 1, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 1, L"abcdefghij", 5, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 1, L"abcdefghij", 9, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 1, L"abcdefghij", 10, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 1, L"abcdefghijklmnopqrst", 0, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 1, L"abcdefghijklmnopqrst", 1, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 1, L"abcdefghijklmnopqrst", 10, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 1, L"abcdefghijklmnopqrst", 19, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 1, L"abcdefghijklmnopqrst", 20, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 9, L"", 0, 9);
    test(S(L"abcdefghijklmnopqrst"), 1, 9, L"abcde", 0, 9);
    test(S(L"abcdefghijklmnopqrst"), 1, 9, L"abcde", 1, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 9, L"abcde", 2, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 9, L"abcde", 4, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 9, L"abcde", 5, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 9, L"abcdefghij", 0, 9);
    test(S(L"abcdefghijklmnopqrst"), 1, 9, L"abcdefghij", 1, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 9, L"abcdefghij", 5, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 9, L"abcdefghij", 9, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 9, L"abcdefghij", 10, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 9, L"abcdefghijklmnopqrst", 0, 9);
    test(S(L"abcdefghijklmnopqrst"), 1, 9, L"abcdefghijklmnopqrst", 1, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 9, L"abcdefghijklmnopqrst", 10, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 9, L"abcdefghijklmnopqrst", 19, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 9, L"abcdefghijklmnopqrst", 20, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 18, L"", 0, 18);
    test(S(L"abcdefghijklmnopqrst"), 1, 18, L"abcde", 0, 18);
    test(S(L"abcdefghijklmnopqrst"), 1, 18, L"abcde", 1, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 18, L"abcde", 2, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 18, L"abcde", 4, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 18, L"abcde", 5, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 18, L"abcdefghij", 0, 18);
    test(S(L"abcdefghijklmnopqrst"), 1, 18, L"abcdefghij", 1, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 18, L"abcdefghij", 5, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 18, L"abcdefghij", 9, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 18, L"abcdefghij", 10, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 18, L"abcdefghijklmnopqrst", 0, 18);
    test(S(L"abcdefghijklmnopqrst"), 1, 18, L"abcdefghijklmnopqrst", 1, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 18, L"abcdefghijklmnopqrst", 10, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 18, L"abcdefghijklmnopqrst", 19, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 18, L"abcdefghijklmnopqrst", 20, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 19, L"", 0, 19);
    test(S(L"abcdefghijklmnopqrst"), 1, 19, L"abcde", 0, 19);
    test(S(L"abcdefghijklmnopqrst"), 1, 19, L"abcde", 1, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 19, L"abcde", 2, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 19, L"abcde", 4, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 19, L"abcde", 5, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 19, L"abcdefghij", 0, 19);
    test(S(L"abcdefghijklmnopqrst"), 1, 19, L"abcdefghij", 1, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 19, L"abcdefghij", 5, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 19, L"abcdefghij", 9, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 19, L"abcdefghij", 10, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 19, L"abcdefghijklmnopqrst", 0, 19);
    test(S(L"abcdefghijklmnopqrst"), 1, 19, L"abcdefghijklmnopqrst", 1, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 19, L"abcdefghijklmnopqrst", 10, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 19, L"abcdefghijklmnopqrst", 19, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 19, L"abcdefghijklmnopqrst", 20, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 20, L"", 0, 19);
    test(S(L"abcdefghijklmnopqrst"), 1, 20, L"abcde", 0, 19);
    test(S(L"abcdefghijklmnopqrst"), 1, 20, L"abcde", 1, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 20, L"abcde", 2, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 20, L"abcde", 4, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 20, L"abcde", 5, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 20, L"abcdefghij", 0, 19);
    test(S(L"abcdefghijklmnopqrst"), 1, 20, L"abcdefghij", 1, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 20, L"abcdefghij", 5, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 20, L"abcdefghij", 9, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 20, L"abcdefghij", 10, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 20, L"abcdefghijklmnopqrst", 0, 19);
    test(S(L"abcdefghijklmnopqrst"), 1, 20, L"abcdefghijklmnopqrst", 1, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 20, L"abcdefghijklmnopqrst", 10, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 20, L"abcdefghijklmnopqrst", 19, 1);
    test(S(L"abcdefghijklmnopqrst"), 1, 20, L"abcdefghijklmnopqrst", 20, 1);
    test(S(L"abcdefghijklmnopqrst"), 10, 0, L"", 0, 0);
    test(S(L"abcdefghijklmnopqrst"), 10, 0, L"abcde", 0, 0);
    test(S(L"abcdefghijklmnopqrst"), 10, 0, L"abcde", 1, -1);
    test(S(L"abcdefghijklmnopqrst"), 10, 0, L"abcde", 2, -2);
    test(S(L"abcdefghijklmnopqrst"), 10, 0, L"abcde", 4, -4);
    test(S(L"abcdefghijklmnopqrst"), 10, 0, L"abcde", 5, -5);
    test(S(L"abcdefghijklmnopqrst"), 10, 0, L"abcdefghij", 0, 0);
    test(S(L"abcdefghijklmnopqrst"), 10, 0, L"abcdefghij", 1, -1);
}

template <class S>
void test10()
{
    test(S(L"abcdefghijklmnopqrst"), 10, 0, L"abcdefghij", 5, -5);
    test(S(L"abcdefghijklmnopqrst"), 10, 0, L"abcdefghij", 9, -9);
    test(S(L"abcdefghijklmnopqrst"), 10, 0, L"abcdefghij", 10, -10);
    test(S(L"abcdefghijklmnopqrst"), 10, 0, L"abcdefghijklmnopqrst", 0, 0);
    test(S(L"abcdefghijklmnopqrst"), 10, 0, L"abcdefghijklmnopqrst", 1, -1);
    test(S(L"abcdefghijklmnopqrst"), 10, 0, L"abcdefghijklmnopqrst", 10, -10);
    test(S(L"abcdefghijklmnopqrst"), 10, 0, L"abcdefghijklmnopqrst", 19, -19);
    test(S(L"abcdefghijklmnopqrst"), 10, 0, L"abcdefghijklmnopqrst", 20, -20);
    test(S(L"abcdefghijklmnopqrst"), 10, 1, L"", 0, 1);
    test(S(L"abcdefghijklmnopqrst"), 10, 1, L"abcde", 0, 1);
    test(S(L"abcdefghijklmnopqrst"), 10, 1, L"abcde", 1, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 1, L"abcde", 2, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 1, L"abcde", 4, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 1, L"abcde", 5, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 1, L"abcdefghij", 0, 1);
    test(S(L"abcdefghijklmnopqrst"), 10, 1, L"abcdefghij", 1, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 1, L"abcdefghij", 5, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 1, L"abcdefghij", 9, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 1, L"abcdefghij", 10, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 1, L"abcdefghijklmnopqrst", 0, 1);
    test(S(L"abcdefghijklmnopqrst"), 10, 1, L"abcdefghijklmnopqrst", 1, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 1, L"abcdefghijklmnopqrst", 10, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 1, L"abcdefghijklmnopqrst", 19, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 1, L"abcdefghijklmnopqrst", 20, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 5, L"", 0, 5);
    test(S(L"abcdefghijklmnopqrst"), 10, 5, L"abcde", 0, 5);
    test(S(L"abcdefghijklmnopqrst"), 10, 5, L"abcde", 1, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 5, L"abcde", 2, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 5, L"abcde", 4, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 5, L"abcde", 5, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 5, L"abcdefghij", 0, 5);
    test(S(L"abcdefghijklmnopqrst"), 10, 5, L"abcdefghij", 1, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 5, L"abcdefghij", 5, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 5, L"abcdefghij", 9, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 5, L"abcdefghij", 10, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 5, L"abcdefghijklmnopqrst", 0, 5);
    test(S(L"abcdefghijklmnopqrst"), 10, 5, L"abcdefghijklmnopqrst", 1, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 5, L"abcdefghijklmnopqrst", 10, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 5, L"abcdefghijklmnopqrst", 19, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 5, L"abcdefghijklmnopqrst", 20, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 9, L"", 0, 9);
    test(S(L"abcdefghijklmnopqrst"), 10, 9, L"abcde", 0, 9);
    test(S(L"abcdefghijklmnopqrst"), 10, 9, L"abcde", 1, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 9, L"abcde", 2, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 9, L"abcde", 4, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 9, L"abcde", 5, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 9, L"abcdefghij", 0, 9);
    test(S(L"abcdefghijklmnopqrst"), 10, 9, L"abcdefghij", 1, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 9, L"abcdefghij", 5, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 9, L"abcdefghij", 9, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 9, L"abcdefghij", 10, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 9, L"abcdefghijklmnopqrst", 0, 9);
    test(S(L"abcdefghijklmnopqrst"), 10, 9, L"abcdefghijklmnopqrst", 1, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 9, L"abcdefghijklmnopqrst", 10, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 9, L"abcdefghijklmnopqrst", 19, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 9, L"abcdefghijklmnopqrst", 20, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 10, L"", 0, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 10, L"abcde", 0, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 10, L"abcde", 1, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 10, L"abcde", 2, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 10, L"abcde", 4, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 10, L"abcde", 5, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 10, L"abcdefghij", 0, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 10, L"abcdefghij", 1, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 10, L"abcdefghij", 5, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 10, L"abcdefghij", 9, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 10, L"abcdefghij", 10, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 10, L"abcdefghijklmnopqrst", 0, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 10, L"abcdefghijklmnopqrst", 1, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 10, L"abcdefghijklmnopqrst", 10, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 10, L"abcdefghijklmnopqrst", 19, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 10, L"abcdefghijklmnopqrst", 20, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 11, L"", 0, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 11, L"abcde", 0, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 11, L"abcde", 1, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 11, L"abcde", 2, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 11, L"abcde", 4, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 11, L"abcde", 5, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 11, L"abcdefghij", 0, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 11, L"abcdefghij", 1, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 11, L"abcdefghij", 5, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 11, L"abcdefghij", 9, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 11, L"abcdefghij", 10, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 11, L"abcdefghijklmnopqrst", 0, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 11, L"abcdefghijklmnopqrst", 1, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 11, L"abcdefghijklmnopqrst", 10, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 11, L"abcdefghijklmnopqrst", 19, 10);
    test(S(L"abcdefghijklmnopqrst"), 10, 11, L"abcdefghijklmnopqrst", 20, 10);
    test(S(L"abcdefghijklmnopqrst"), 19, 0, L"", 0, 0);
    test(S(L"abcdefghijklmnopqrst"), 19, 0, L"abcde", 0, 0);
    test(S(L"abcdefghijklmnopqrst"), 19, 0, L"abcde", 1, -1);
    test(S(L"abcdefghijklmnopqrst"), 19, 0, L"abcde", 2, -2);
    test(S(L"abcdefghijklmnopqrst"), 19, 0, L"abcde", 4, -4);
    test(S(L"abcdefghijklmnopqrst"), 19, 0, L"abcde", 5, -5);
    test(S(L"abcdefghijklmnopqrst"), 19, 0, L"abcdefghij", 0, 0);
    test(S(L"abcdefghijklmnopqrst"), 19, 0, L"abcdefghij", 1, -1);
    test(S(L"abcdefghijklmnopqrst"), 19, 0, L"abcdefghij", 5, -5);
    test(S(L"abcdefghijklmnopqrst"), 19, 0, L"abcdefghij", 9, -9);
    test(S(L"abcdefghijklmnopqrst"), 19, 0, L"abcdefghij", 10, -10);
    test(S(L"abcdefghijklmnopqrst"), 19, 0, L"abcdefghijklmnopqrst", 0, 0);
}

template <class S>
void test11()
{
    test(S(L"abcdefghijklmnopqrst"), 19, 0, L"abcdefghijklmnopqrst", 1, -1);
    test(S(L"abcdefghijklmnopqrst"), 19, 0, L"abcdefghijklmnopqrst", 10, -10);
    test(S(L"abcdefghijklmnopqrst"), 19, 0, L"abcdefghijklmnopqrst", 19, -19);
    test(S(L"abcdefghijklmnopqrst"), 19, 0, L"abcdefghijklmnopqrst", 20, -20);
    test(S(L"abcdefghijklmnopqrst"), 19, 1, L"", 0, 1);
    test(S(L"abcdefghijklmnopqrst"), 19, 1, L"abcde", 0, 1);
    test(S(L"abcdefghijklmnopqrst"), 19, 1, L"abcde", 1, 19);
    test(S(L"abcdefghijklmnopqrst"), 19, 1, L"abcde", 2, 19);
    test(S(L"abcdefghijklmnopqrst"), 19, 1, L"abcde", 4, 19);
    test(S(L"abcdefghijklmnopqrst"), 19, 1, L"abcde", 5, 19);
    test(S(L"abcdefghijklmnopqrst"), 19, 1, L"abcdefghij", 0, 1);
    test(S(L"abcdefghijklmnopqrst"), 19, 1, L"abcdefghij", 1, 19);
    test(S(L"abcdefghijklmnopqrst"), 19, 1, L"abcdefghij", 5, 19);
    test(S(L"abcdefghijklmnopqrst"), 19, 1, L"abcdefghij", 9, 19);
    test(S(L"abcdefghijklmnopqrst"), 19, 1, L"abcdefghij", 10, 19);
    test(S(L"abcdefghijklmnopqrst"), 19, 1, L"abcdefghijklmnopqrst", 0, 1);
    test(S(L"abcdefghijklmnopqrst"), 19, 1, L"abcdefghijklmnopqrst", 1, 19);
    test(S(L"abcdefghijklmnopqrst"), 19, 1, L"abcdefghijklmnopqrst", 10, 19);
    test(S(L"abcdefghijklmnopqrst"), 19, 1, L"abcdefghijklmnopqrst", 19, 19);
    test(S(L"abcdefghijklmnopqrst"), 19, 1, L"abcdefghijklmnopqrst", 20, 19);
    test(S(L"abcdefghijklmnopqrst"), 19, 2, L"", 0, 1);
    test(S(L"abcdefghijklmnopqrst"), 19, 2, L"abcde", 0, 1);
    test(S(L"abcdefghijklmnopqrst"), 19, 2, L"abcde", 1, 19);
    test(S(L"abcdefghijklmnopqrst"), 19, 2, L"abcde", 2, 19);
    test(S(L"abcdefghijklmnopqrst"), 19, 2, L"abcde", 4, 19);
    test(S(L"abcdefghijklmnopqrst"), 19, 2, L"abcde", 5, 19);
    test(S(L"abcdefghijklmnopqrst"), 19, 2, L"abcdefghij", 0, 1);
    test(S(L"abcdefghijklmnopqrst"), 19, 2, L"abcdefghij", 1, 19);
    test(S(L"abcdefghijklmnopqrst"), 19, 2, L"abcdefghij", 5, 19);
    test(S(L"abcdefghijklmnopqrst"), 19, 2, L"abcdefghij", 9, 19);
    test(S(L"abcdefghijklmnopqrst"), 19, 2, L"abcdefghij", 10, 19);
    test(S(L"abcdefghijklmnopqrst"), 19, 2, L"abcdefghijklmnopqrst", 0, 1);
    test(S(L"abcdefghijklmnopqrst"), 19, 2, L"abcdefghijklmnopqrst", 1, 19);
    test(S(L"abcdefghijklmnopqrst"), 19, 2, L"abcdefghijklmnopqrst", 10, 19);
    test(S(L"abcdefghijklmnopqrst"), 19, 2, L"abcdefghijklmnopqrst", 19, 19);
    test(S(L"abcdefghijklmnopqrst"), 19, 2, L"abcdefghijklmnopqrst", 20, 19);
    test(S(L"abcdefghijklmnopqrst"), 20, 0, L"", 0, 0);
    test(S(L"abcdefghijklmnopqrst"), 20, 0, L"abcde", 0, 0);
    test(S(L"abcdefghijklmnopqrst"), 20, 0, L"abcde", 1, -1);
    test(S(L"abcdefghijklmnopqrst"), 20, 0, L"abcde", 2, -2);
    test(S(L"abcdefghijklmnopqrst"), 20, 0, L"abcde", 4, -4);
    test(S(L"abcdefghijklmnopqrst"), 20, 0, L"abcde", 5, -5);
    test(S(L"abcdefghijklmnopqrst"), 20, 0, L"abcdefghij", 0, 0);
    test(S(L"abcdefghijklmnopqrst"), 20, 0, L"abcdefghij", 1, -1);
    test(S(L"abcdefghijklmnopqrst"), 20, 0, L"abcdefghij", 5, -5);
    test(S(L"abcdefghijklmnopqrst"), 20, 0, L"abcdefghij", 9, -9);
    test(S(L"abcdefghijklmnopqrst"), 20, 0, L"abcdefghij", 10, -10);
    test(S(L"abcdefghijklmnopqrst"), 20, 0, L"abcdefghijklmnopqrst", 0, 0);
    test(S(L"abcdefghijklmnopqrst"), 20, 0, L"abcdefghijklmnopqrst", 1, -1);
    test(S(L"abcdefghijklmnopqrst"), 20, 0, L"abcdefghijklmnopqrst", 10, -10);
    test(S(L"abcdefghijklmnopqrst"), 20, 0, L"abcdefghijklmnopqrst", 19, -19);
    test(S(L"abcdefghijklmnopqrst"), 20, 0, L"abcdefghijklmnopqrst", 20, -20);
    test(S(L"abcdefghijklmnopqrst"), 20, 1, L"", 0, 0);
    test(S(L"abcdefghijklmnopqrst"), 20, 1, L"abcde", 0, 0);
    test(S(L"abcdefghijklmnopqrst"), 20, 1, L"abcde", 1, -1);
    test(S(L"abcdefghijklmnopqrst"), 20, 1, L"abcde", 2, -2);
    test(S(L"abcdefghijklmnopqrst"), 20, 1, L"abcde", 4, -4);
    test(S(L"abcdefghijklmnopqrst"), 20, 1, L"abcde", 5, -5);
    test(S(L"abcdefghijklmnopqrst"), 20, 1, L"abcdefghij", 0, 0);
    test(S(L"abcdefghijklmnopqrst"), 20, 1, L"abcdefghij", 1, -1);
    test(S(L"abcdefghijklmnopqrst"), 20, 1, L"abcdefghij", 5, -5);
    test(S(L"abcdefghijklmnopqrst"), 20, 1, L"abcdefghij", 9, -9);
    test(S(L"abcdefghijklmnopqrst"), 20, 1, L"abcdefghij", 10, -10);
    test(S(L"abcdefghijklmnopqrst"), 20, 1, L"abcdefghijklmnopqrst", 0, 0);
    test(S(L"abcdefghijklmnopqrst"), 20, 1, L"abcdefghijklmnopqrst", 1, -1);
    test(S(L"abcdefghijklmnopqrst"), 20, 1, L"abcdefghijklmnopqrst", 10, -10);
    test(S(L"abcdefghijklmnopqrst"), 20, 1, L"abcdefghijklmnopqrst", 19, -19);
    test(S(L"abcdefghijklmnopqrst"), 20, 1, L"abcdefghijklmnopqrst", 20, -20);
    test(S(L"abcdefghijklmnopqrst"), 21, 0, L"", 0, 0);
    test(S(L"abcdefghijklmnopqrst"), 21, 0, L"abcde", 0, 0);
    test(S(L"abcdefghijklmnopqrst"), 21, 0, L"abcde", 1, 0);
    test(S(L"abcdefghijklmnopqrst"), 21, 0, L"abcde", 2, 0);
    test(S(L"abcdefghijklmnopqrst"), 21, 0, L"abcde", 4, 0);
    test(S(L"abcdefghijklmnopqrst"), 21, 0, L"abcde", 5, 0);
    test(S(L"abcdefghijklmnopqrst"), 21, 0, L"abcdefghij", 0, 0);
    test(S(L"abcdefghijklmnopqrst"), 21, 0, L"abcdefghij", 1, 0);
    test(S(L"abcdefghijklmnopqrst"), 21, 0, L"abcdefghij", 5, 0);
    test(S(L"abcdefghijklmnopqrst"), 21, 0, L"abcdefghij", 9, 0);
    test(S(L"abcdefghijklmnopqrst"), 21, 0, L"abcdefghij", 10, 0);
    test(S(L"abcdefghijklmnopqrst"), 21, 0, L"abcdefghijklmnopqrst", 0, 0);
    test(S(L"abcdefghijklmnopqrst"), 21, 0, L"abcdefghijklmnopqrst", 1, 0);
    test(S(L"abcdefghijklmnopqrst"), 21, 0, L"abcdefghijklmnopqrst", 10, 0);
    test(S(L"abcdefghijklmnopqrst"), 21, 0, L"abcdefghijklmnopqrst", 19, 0);
    test(S(L"abcdefghijklmnopqrst"), 21, 0, L"abcdefghijklmnopqrst", 20, 0);
}

int main()
{
    {
    typedef barefootc::basic_string<wchar_t> S;
    test0<S>();
    test1<S>();
    test2<S>();
    test3<S>();
    test4<S>();
    test5<S>();
    test6<S>();
    test7<S>();
    test8<S>();
    test9<S>();
    test10<S>();
    test11<S>();
    }
#if __cplusplus >= 201103L
    {
    typedef barefootc::basic_string<char, std::char_traits<char>, min_allocator<char>> S;
    test0<S>();
    test1<S>();
    test2<S>();
    test3<S>();
    test4<S>();
    test5<S>();
    test6<S>();
    test7<S>();
    test8<S>();
    test9<S>();
    test10<S>();
    test11<S>();
    }
#endif
}
