
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include <wchar.h>

#include <inttypes.h>

#include "barefootc/object.h"
#include "barefootc/string.h"

#define STRING_CLASS_NAME			"shared_string"

#define	wchar_t					char
#define bfc_shared_wstring			bfc_shared_string

#define bfc_wstring_class			bfc_string_class
#define bfc_shared_wstring_class			bfc_shared_string_class
#define bfc_wchar_traits_class			bfc_char_traits_class

#define	bfc_init_shared_wstring			bfc_init_shared_string
#define	bfc_destroy_shared_wstring		bfc_destroy_shared_string
#define	bfc_shared_wstring_objsize		bfc_shared_string_objsize
#define	bfc_init_shared_wstring_copy		bfc_init_shared_string_copy
#define	bfc_init_shared_wstring_move		bfc_init_shared_string_move
#define	bfc_init_shared_wstring_substr		bfc_init_shared_string_substr
#define	bfc_init_shared_wstring_buffer		bfc_init_shared_string_buffer
#define	bfc_init_shared_wstring_c_str		bfc_init_shared_string_c_str
#define	bfc_init_shared_wstring_fill		bfc_init_shared_string_fill
#define	bfc_init_shared_wstring_range		bfc_init_shared_string_range
#define	bfc_shared_wstring_length		bfc_shared_string_length
#define	bfc_shared_wstring_max_size		bfc_shared_string_max_size
#define	bfc_shared_wstring_resize		bfc_shared_string_resize
#define	bfc_shared_wstring_capacity		bfc_shared_string_capacity
#define	bfc_shared_wstring_reserve		bfc_shared_string_reserve

#define	bfc_shared_wstring_assign_copy		bfc_shared_string_assign_copy
#define	bfc_shared_wstring_assign_substr	bfc_shared_string_assign_substr
#define	bfc_shared_wstring_assign_c_str		bfc_shared_string_assign_c_str
#define	bfc_shared_wstring_assign_buffer	bfc_shared_string_assign_buffer
#define	bfc_shared_wstring_assign_fill		bfc_shared_string_assign_fill
#define	bfc_shared_wstring_assign_range		bfc_shared_string_assign_range
#define	bfc_shared_wstring_append_copy		bfc_shared_string_append_copy
#define	bfc_shared_wstring_append_substr	bfc_shared_string_append_substr
#define	bfc_shared_wstring_append_c_str		bfc_shared_string_append_c_str
#define	bfc_shared_wstring_append_buffer	bfc_shared_string_append_buffer
#define	bfc_shared_wstring_append_fill		bfc_shared_string_append_fill
#define	bfc_shared_wstring_append_range		bfc_shared_string_append_range
#define	bfc_shared_wstring_push_back		bfc_shared_string_push_back
#define	bfc_shared_wstring_insert_copy		bfc_shared_string_insert_copy
#define	bfc_shared_wstring_insert_substr	bfc_shared_string_insert_substr
#define	bfc_shared_wstring_insert_c_str		bfc_shared_string_insert_c_str
#define	bfc_shared_wstring_insert_buffer	bfc_shared_string_insert_buffer
#define	bfc_shared_wstring_insert_fill		bfc_shared_string_insert_fill
#define	bfc_shared_wstring_insert_fillit	bfc_shared_string_insert_fillit
#define	bfc_shared_wstring_insert_char		bfc_shared_string_insert_char
#define	bfc_shared_wstring_insert_range		bfc_shared_string_insert_range
#define	bfc_shared_wstring_erase_seq		bfc_shared_string_erase_seq
#define	bfc_shared_wstring_erase_tail		bfc_shared_string_erase_tail
#define	bfc_shared_wstring_erase_char		bfc_shared_string_erase_char
#define	bfc_shared_wstring_erase_range		bfc_shared_string_erase_range
#define	bfc_shared_wstring_pop_back		bfc_shared_string_pop_back
#define	bfc_shared_wstring_replace_copy		bfc_shared_string_replace_copy
#define	bfc_shared_wstring_replace_substr	bfc_shared_string_replace_substr
#define	bfc_shared_wstring_replace_buffer	bfc_shared_string_replace_buffer
#define	bfc_shared_wstring_replace_c_str	bfc_shared_string_replace_c_str
#define	bfc_shared_wstring_replace_fill		bfc_shared_string_replace_fill
#define	bfc_shared_wstring_replace_range_copy	bfc_shared_string_replace_range_copy
#define	bfc_shared_wstring_replace_range_buffer	bfc_shared_string_replace_range_buffer
#define	bfc_shared_wstring_replace_range_c_str	bfc_shared_string_replace_range_c_str
#define	bfc_shared_wstring_replace_range_fill	bfc_shared_string_replace_range_fill
#define	bfc_shared_wstring_replace_ranges	bfc_shared_string_replace_ranges

#define	bfc_wstring_length			bfc_cstring_length
#define	bfc_basic_wstring_max_size		bfc_basic_string_max_size

#define	bfc_wstrlen				bfc_strlen
#define	bfc_wstrbuf				bfc_strbuf
#define	bfc_wstrdata				bfc_strdata
#define	bfc_wstring_sublen			bfc_string_sublen
#define	bfc_wstr_reserve			bfc_str_reserve

#include "shared_wstring.c"

